//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Microsoft.WindowsAzure.Commands.ServiceManagement.IaaS {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration", IsNullable=false)]
    public partial class NetworkConfiguration {
        
        private VirtualNetworkConfiguration virtualNetworkConfigurationField;
        
        /// <remarks/>
        public VirtualNetworkConfiguration VirtualNetworkConfiguration {
            get {
                return this.virtualNetworkConfigurationField;
            }
            set {
                this.virtualNetworkConfigurationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
    public partial class VirtualNetworkConfiguration {
        
        private Dns dnsField;
        
        private LocalNetworkSite[] localNetworkSitesField;
        
        private VirtualNetworkSite[] virtualNetworkSitesField;
        
        /// <remarks/>
        public Dns Dns {
            get {
                return this.dnsField;
            }
            set {
                this.dnsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public LocalNetworkSite[] LocalNetworkSites {
            get {
                return this.localNetworkSitesField;
            }
            set {
                this.localNetworkSitesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public VirtualNetworkSite[] VirtualNetworkSites {
            get {
                return this.virtualNetworkSitesField;
            }
            set {
                this.virtualNetworkSitesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
    public partial class Dns {
        
        private DnsServer[] dnsServersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DnsServer[] DnsServers {
            get {
                return this.dnsServersField;
            }
            set {
                this.dnsServersField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
    public partial class DnsServer {
        
        private string nameField;
        
        private string iPAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
    public partial class InternetGatewayNetwork {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
    public partial class Connection {
        
        private ConnectionType typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ConnectionType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
    public enum ConnectionType {
        
        /// <remarks/>
        IPsec,
        
        /// <remarks/>
        Dedicated,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
    public partial class LocalNetworkSiteRef {
        
        private Connection[] connectionField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Connection")]
        public Connection[] Connection {
            get {
                return this.connectionField;
            }
            set {
                this.connectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
    public partial class Gateway {
        
        private string[] vPNClientAddressPoolField;
        
        private LocalNetworkSiteRef[] connectionsToLocalNetworkField;
        
        private GatewaySize profileField;
        
        public Gateway() {
            this.profileField = GatewaySize.Small;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AddressPrefix", IsNullable=false)]
        public string[] VPNClientAddressPool {
            get {
                return this.vPNClientAddressPoolField;
            }
            set {
                this.vPNClientAddressPoolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public LocalNetworkSiteRef[] ConnectionsToLocalNetwork {
            get {
                return this.connectionsToLocalNetworkField;
            }
            set {
                this.connectionsToLocalNetworkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(GatewaySize.Small)]
        public GatewaySize profile {
            get {
                return this.profileField;
            }
            set {
                this.profileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
    public enum GatewaySize {
        
        /// <remarks/>
        Small,
        
        /// <remarks/>
        Medium,
        
        /// <remarks/>
        Large,
        
        /// <remarks/>
        ExtraLarge,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
    public partial class DnsServerRef {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
    public partial class Subnet {
        
        private string addressPrefixField;
        
        private string nameField;
        
        /// <remarks/>
        public string AddressPrefix {
            get {
                return this.addressPrefixField;
            }
            set {
                this.addressPrefixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
    public partial class VirtualNetworkSite {
        
        private string[] addressSpaceField;
        
        private Subnet[] subnetsField;
        
        private DnsServerRef[] dnsServersRefField;
        
        private Gateway gatewayField;
        
        private InternetGatewayNetwork internetGatewayNetworkField;
        
        private string nameField;
        
        private string affinityGroupField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AddressPrefix", IsNullable=false)]
        public string[] AddressSpace {
            get {
                return this.addressSpaceField;
            }
            set {
                this.addressSpaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Subnet[] Subnets {
            get {
                return this.subnetsField;
            }
            set {
                this.subnetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DnsServerRef[] DnsServersRef {
            get {
                return this.dnsServersRefField;
            }
            set {
                this.dnsServersRefField = value;
            }
        }
        
        /// <remarks/>
        public Gateway Gateway {
            get {
                return this.gatewayField;
            }
            set {
                this.gatewayField = value;
            }
        }
        
        /// <remarks/>
        public InternetGatewayNetwork InternetGatewayNetwork {
            get {
                return this.internetGatewayNetworkField;
            }
            set {
                this.internetGatewayNetworkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AffinityGroup {
            get {
                return this.affinityGroupField;
            }
            set {
                this.affinityGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/ServiceHosting/2011/07/NetworkConfiguration")]
    public partial class LocalNetworkSite {
        
        private string[] addressSpaceField;
        
        private string vPNGatewayAddressField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("AddressPrefix", IsNullable=false)]
        public string[] AddressSpace {
            get {
                return this.addressSpaceField;
            }
            set {
                this.addressSpaceField = value;
            }
        }
        
        /// <remarks/>
        public string VPNGatewayAddress {
            get {
                return this.vPNGatewayAddressField;
            }
            set {
                this.vPNGatewayAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
}
