//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAzure.Commands.ServiceManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAzure.Commands.ServiceManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAS Uri for the destination blob is not supported in patch mode:{0}.
        /// </summary>
        internal static string AddAzureVhdCommandSASUriNotSupportedInPatchMode {
            get {
                return ResourceManager.GetString("AddAzureVhdCommandSASUriNotSupportedInPatchMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an WinRM Http Listener in ProvisioningConfiguration.
        /// </summary>
        internal static string AlreadyExistingWinRMHttpListener {
            get {
                return ResourceManager.GetString("AlreadyExistingWinRMHttpListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an WinRM Https Listener in ProvisioningConfiguration.
        /// </summary>
        internal static string AlreadyExistingWinRMHttpsListener {
            get {
                return ResourceManager.GetString("AlreadyExistingWinRMHttpsListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Operation: {0}.
        /// </summary>
        internal static string AzureRemoteDesktopBeginOperation {
            get {
                return ResourceManager.GetString("AzureRemoteDesktopBeginOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Operation: {0}.
        /// </summary>
        internal static string AzureRemoteDesktopCompletedOperation {
            get {
                return ResourceManager.GetString("AzureRemoteDesktopCompletedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Operation: {0}.
        /// </summary>
        internal static string AzureVMBeginOperation {
            get {
                return ResourceManager.GetString("AzureVMBeginOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Create Deployment with VM {1}.
        /// </summary>
        internal static string AzureVMCommandCreateDeploymentWithVM {
            get {
                return ResourceManager.GetString("AzureVMCommandCreateDeploymentWithVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Create VM {1}.
        /// </summary>
        internal static string AzureVMCommandCreateVM {
            get {
                return ResourceManager.GetString("AzureVMCommandCreateVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Uploading Certificate: {1}.
        /// </summary>
        internal static string AzureVMCommandUploadingCertificate {
            get {
                return ResourceManager.GetString("AzureVMCommandUploadingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Operation: {0}.
        /// </summary>
        internal static string AzureVMCompletedOperation {
            get {
                return ResourceManager.GetString("AzureVMCompletedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Uploading WinRMCertificate: {1}.
        /// </summary>
        internal static string AzureVMUploadingWinRMCertificate {
            get {
                return ResourceManager.GetString("AzureVMUploadingWinRMCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Operation: {0}.
        /// </summary>
        internal static string AzureVNetConfigBeginOperation {
            get {
                return ResourceManager.GetString("AzureVNetConfigBeginOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Operation: {0}.
        /// </summary>
        internal static string AzureVNetConfigCompletedOperation {
            get {
                return ResourceManager.GetString("AzureVNetConfigCompletedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Operation: {0}.
        /// </summary>
        internal static string AzureVNetSiteBeginOperation {
            get {
                return ResourceManager.GetString("AzureVNetSiteBeginOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Operation: {0}.
        /// </summary>
        internal static string AzureVNetSiteCompletedOperation {
            get {
                return ResourceManager.GetString("AzureVNetSiteCompletedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Create New Deployment with Virtual Machines Present in {0} Slot.
        /// </summary>
        internal static string CanNotCreateNewDeploymentWhileVMsArePresent {
            get {
                return ResourceManager.GetString("CanNotCreateNewDeploymentWhileVMsArePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Move Deployments with Virtual Machines Present in {0}.
        /// </summary>
        internal static string CanNotMoveDeploymentsWhileVMsArePresent {
            get {
                return ResourceManager.GetString("CanNotMoveDeploymentsWhileVMsArePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a deployment for &apos;{0}&apos; in &apos;{1}&apos; slot..
        /// </summary>
        internal static string CouldNotFindDeployment {
            get {
                return ResourceManager.GetString("CouldNotFindDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the new deployment.
        /// </summary>
        internal static string CreatingNewDeployment {
            get {
                return ResourceManager.GetString("CreatingNewDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current deployment doesn&apos;t have any Url.
        /// </summary>
        internal static string CurrentDeploymentDoesNotHaveUrl {
            get {
                return ResourceManager.GetString("CurrentDeploymentDoesNotHaveUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current deployment doesn&apos;t have any VMs.
        /// </summary>
        internal static string CurrentDeploymentDoesNotHaveVMs {
            get {
                return ResourceManager.GetString("CurrentDeploymentDoesNotHaveVMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentStorageAccountName is not accessible. Ensure the current storage account is accessible and in the same location or affinity group as your cloud service..
        /// </summary>
        internal static string CurrentStorageAccountIsNotAccessible {
            get {
                return ResourceManager.GetString("CurrentStorageAccountIsNotAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentStorageAccountName is not set. Use Set-AzureSubscription subname -CurrentStorageAccountName storageaccount to set it..
        /// </summary>
        internal static string CurrentStorageAccountIsNotSet {
            get {
                return ResourceManager.GetString("CurrentStorageAccountIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data disk is not currently assigned to LUN #{0} in the configuration of this VM..
        /// </summary>
        internal static string DataDiskAlreadyAssignedInVMConfiguration {
            get {
                return ResourceManager.GetString("DataDiskAlreadyAssignedInVMConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data disk has already been assigned to LUN #{0} for this VM. Specify a different LUN or use Set-DataDisk to change the configuration settings of the existing disk..
        /// </summary>
        internal static string DataDiskAlreadySpecifiedForVM {
            get {
                return ResourceManager.GetString("DataDiskAlreadySpecifiedForVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data disk is not currently assigned to LUN #{0} for this VM. Use New-DataDisk to define it..
        /// </summary>
        internal static string DataDiskNotAssignedForVM {
            get {
                return ResourceManager.GetString("DataDiskNotAssignedForVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cmdlet will remove deployed applications including VMs from the specified deployment slot. Do you want to continue?.
        /// </summary>
        internal static string DeployedArtifactsWillBeRemoved {
            get {
                return ResourceManager.GetString("DeployedArtifactsWillBeRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment Deletion.
        /// </summary>
        internal static string DeploymentDeletion {
            get {
                return ResourceManager.GetString("DeploymentDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified virtual machine is the last virtual machine in this deployment. Continuing will result in a new IP address for your deployment. To shut down without losing the deployment IP use –StayProvisioned..
        /// </summary>
        internal static string DeploymentVIPLossWarning {
            get {
                return ResourceManager.GetString("DeploymentVIPLossWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deprovisioning the VM: {0} .
        /// </summary>
        internal static string DeprovisioningVM {
            get {
                return ResourceManager.GetString("DeprovisioningVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location or AffinityGroup, only one of them needs to be specified..
        /// </summary>
        internal static string EitherLocationOrAffinityGroupBeSpecified {
            get {
                return ResourceManager.GetString("EitherLocationOrAffinityGroupBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An endpoint named &apos;{0}&apos; has already been defined for this VM. Specify a different endpoint name or use Set-Endpoint to change the configuration settings of the existing endpoint..
        /// </summary>
        internal static string EndpointAlreadyDefinedForVM {
            get {
                return ResourceManager.GetString("EndpointAlreadyDefinedForVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An endpoint named &apos;{0}&apos; cannot be found in the configuration of this VM..
        /// </summary>
        internal static string EndpointCanNotBeFoundInVMConfiguration {
            get {
                return ResourceManager.GetString("EndpointCanNotBeFoundInVMConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An endpoint named &apos;{0}&apos; cannot be found in the configuration of this VM. Use New-ExternalEndpoint to define it..
        /// </summary>
        internal static string EndpointCanNotBeFoundInVMConfigurationInSetAzureEndpoint {
            get {
                return ResourceManager.GetString("EndpointCanNotBeFoundInVMConfigurationInSetAzureEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An endpoint cannot be found with the given load balancer set name &apos;{0}&apos;..
        /// </summary>
        internal static string EndpointsCannotBeFoundWithGivenLBSetName {
            get {
                return ResourceManager.GetString("EndpointsCannotBeFoundWithGivenLBSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Status: .
        /// </summary>
        internal static string GatewayOperationStatus {
            get {
                return ResourceManager.GetString("GatewayOperationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Operation: Get Deployment.
        /// </summary>
        internal static string GetDeploymentBeginOperation {
            get {
                return ResourceManager.GetString("GetDeploymentBeginOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Operation: Get Deployment.
        /// </summary>
        internal static string GetDeploymentCompletedOperation {
            get {
                return ResourceManager.GetString("GetDeploymentCompletedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Status Code: {0} - HTTP Error Message: {1}.
        /// </summary>
        internal static string HttpStatusCodeAndErrorMessage {
            get {
                return ResourceManager.GetString("HttpStatusCodeAndErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Name is invalid..
        /// </summary>
        internal static string InvalidComputerName {
            get {
                return ResourceManager.GetString("InvalidComputerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidateSetFailure - Invalid UpgradeType is specified: &apos;{0}&apos;, valid values are: &apos;{1}&apos;.
        /// </summary>
        internal static string InvalidDeploymentUpgradeType {
            get {
                return ResourceManager.GetString("InvalidDeploymentUpgradeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname is invalid..
        /// </summary>
        internal static string InvalidHostName {
            get {
                return ResourceManager.GetString("InvalidHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify the thumbprint algorithm..
        /// </summary>
        internal static string InvalidThumbprint {
            get {
                return ResourceManager.GetString("InvalidThumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidateSetFailure - Invalid VM Size specified: &apos;{0}&apos;, valid values are: &apos;{1}&apos;.
        /// </summary>
        internal static string InvalidVMSize {
            get {
                return ResourceManager.GetString("InvalidVMSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify a value for either Label or Description..
        /// </summary>
        internal static string LabelOrDescriptionMustBeSpecified {
            get {
                return ResourceManager.GetString("LabelOrDescriptionMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location or AffinityGroup can only be specified when creating a new cloud service..
        /// </summary>
        internal static string LocationOrAffinityGroupCanOnlyBeSpecifiedWhenNewCloudService {
            get {
                return ResourceManager.GetString("LocationOrAffinityGroupCanOnlyBeSpecifiedWhenNewCloudService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location or AffinityGroup is required when creating a new Cloud Service..
        /// </summary>
        internal static string LocationOrAffinityGroupRequiredWhenCreatingNewCloudService {
            get {
                return ResourceManager.GetString("LocationOrAffinityGroupRequiredWhenCreatingNewCloudService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify MediaLocation or set a default storage account using Set-AzureSubscription..
        /// </summary>
        internal static string MediaLocationOrDefaultStorageAccountMustBeSpecified {
            get {
                return ResourceManager.GetString("MediaLocationOrDefaultStorageAccountMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file to load the role does not exist.
        /// </summary>
        internal static string MissingPersistentVMFile {
            get {
                return ResourceManager.GetString("MissingPersistentVMFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role cannot be null.
        /// </summary>
        internal static string MissingPersistentVMRole {
            get {
                return ResourceManager.GetString("MissingPersistentVMRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinRMCertificate must have private key.
        /// </summary>
        internal static string MissingPrivateKeyInWinRMCertificate {
            get {
                return ResourceManager.GetString("MissingPrivateKeyInWinRMCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify the thumbprint algorithm..
        /// </summary>
        internal static string MissingThumbprintAlgorithm {
            get {
                return ResourceManager.GetString("MissingThumbprintAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no WinRM Https Listener in ProvisioningConfiguration.
        /// </summary>
        internal static string MissingWinRMHttpsListener {
            get {
                return ResourceManager.GetString("MissingWinRMHttpsListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moving deployment from Staging to Production:{0}.
        /// </summary>
        internal static string MovingDeploymentFromStagingToProduction {
            get {
                return ResourceManager.GetString("MovingDeploymentFromStagingToProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must provide the Force switch when using wildcard syntax..
        /// </summary>
        internal static string MustSpecifyForceParameterWhenUsingWildcards {
            get {
                return ResourceManager.GetString("MustSpecifyForceParameterWhenUsingWildcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify MediaLocation or set a current storage account using Set-AzureSubscription..
        /// </summary>
        internal static string MustSpecifyMediaLocationOrHaveCurrentStorageAccount {
            get {
                return ResourceManager.GetString("MustSpecifyMediaLocationOrHaveCurrentStorageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must specify the same affinity group as the virtual network is deployed to..
        /// </summary>
        internal static string MustSpecifySameAffinityGroupAsVirtualNetwork {
            get {
                return ResourceManager.GetString("MustSpecifySameAffinityGroupAsVirtualNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network configuration cannot be deserialized..
        /// </summary>
        internal static string NetworkConfigurationCannotBeDeserialized {
            get {
                return ResourceManager.GetString("NetworkConfigurationCannotBeDeserialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory specified to export the network configuration does not exist..
        /// </summary>
        internal static string NetworkConfigurationDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("NetworkConfigurationDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified network configuration file path does not exist..
        /// </summary>
        internal static string NetworkConfigurationFilePathDoesNotExist {
            get {
                return ResourceManager.GetString("NetworkConfigurationFilePathDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Service is not present or there is no virtual machine deployment..
        /// </summary>
        internal static string NoCloudServicePresent {
            get {
                return ResourceManager.GetString("NoCloudServicePresent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No role can be found in the deployment with &apos;{0}&apos; name.
        /// </summary>
        internal static string NoCorrespondingRoleCanBeFoundInDeployment {
            get {
                return ResourceManager.GetString("NoCorrespondingRoleCanBeFoundInDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No deployment found in {0}.
        /// </summary>
        internal static string NoDeploymentFoundToMove {
            get {
                return ResourceManager.GetString("NoDeploymentFoundToMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No deployment found in Staging: {0}.
        /// </summary>
        internal static string NoDeploymentInStaging {
            get {
                return ResourceManager.GetString("NoDeploymentInStaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No deployment found in Staging or Production: {0}.
        /// </summary>
        internal static string NoDeploymentInStagingOrProduction {
            get {
                return ResourceManager.GetString("NoDeploymentInStagingOrProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No endpoint found for the VM: {0}.
        /// </summary>
        internal static string NoEndpointFoundForVM {
            get {
                return ResourceManager.GetString("NoEndpointFoundForVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An OSDisk has not been defined for this VM. Use New-OSDisk to assign a new OS disk..
        /// </summary>
        internal static string OSDiskNotDefinedForVM {
            get {
                return ResourceManager.GetString("OSDiskNotDefinedForVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not meet complexity requirements..
        /// </summary>
        internal static string PasswordNotComplexEnough {
            get {
                return ResourceManager.GetString("PasswordNotComplexEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pfx.
        /// </summary>
        internal static string Pfx_CertificateFormat {
            get {
                return ResourceManager.GetString("Pfx_CertificateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ports must be in the range of 0 - 65535.
        /// </summary>
        internal static string PortsNotInRangeInSetAzureEndpoint {
            get {
                return ResourceManager.GetString("PortsNotInRangeInSetAzureEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ports must be in the range of 1 - 65535.
        /// </summary>
        internal static string PortSpecifiedIsNotInRange {
            get {
                return ResourceManager.GetString("PortSpecifiedIsNotInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProbePath not valid with tcp.
        /// </summary>
        internal static string ProbePathIsNotValidWithTcp {
            get {
                return ResourceManager.GetString("ProbePathIsNotValidWithTcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProbePath is required for http.
        /// </summary>
        internal static string ProbePathIsRequiredForHttp {
            get {
                return ResourceManager.GetString("ProbePathIsRequiredForHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculating MD5 Hash.
        /// </summary>
        internal static string PSSyncOutputEventsCalculatingMD5Hash {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsCalculatingMD5Hash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5 hash is being calculated for the file &apos;{0}&apos;..
        /// </summary>
        internal static string PSSyncOutputEventsCalculatingMD5HashForFile {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsCalculatingMD5HashForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying.
        /// </summary>
        internal static string PSSyncOutputEventsCopying {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsCopying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating new page blob of size {0}....
        /// </summary>
        internal static string PSSyncOutputEventsCreatingNewPageBlob {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsCreatingNewPageBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting the empty data blocks in the local file..
        /// </summary>
        internal static string PSSyncOutputEventsDetectingActualDataBlocks {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsDetectingActualDataBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting the empty data blocks completed..
        /// </summary>
        internal static string PSSyncOutputEventsDetectingActualDataBlocksCompleted {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsDetectingActualDataBlocksCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string PSSyncOutputEventsDownloading {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time for copy: {0}.
        /// </summary>
        internal static string PSSyncOutputEventsElapsedTimeForCopy {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsElapsedTimeForCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time for download: {0}.
        /// </summary>
        internal static string PSSyncOutputEventsElapsedTimeForDownload {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsElapsedTimeForDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time for the operation: {0}.
        /// </summary>
        internal static string PSSyncOutputEventsElapsedTimeForOperation {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsElapsedTimeForOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed time for upload: {0}.
        /// </summary>
        internal static string PSSyncOutputEventsElapsedTimeForUpload {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsElapsedTimeForUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty block detected: {0}.
        /// </summary>
        internal static string PSSyncOutputEventsEmptyBlockDetected {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsEmptyBlockDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string PSSyncOutputEventsEmptyBlockDetectionCompleted {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsEmptyBlockDetectionCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting empty blocks.
        /// </summary>
        internal static string PSSyncOutputEventsEmptyBlockDetectionDetecting {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsEmptyBlockDetectionDetecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days {1:00}:{2:00}:{3:00}.
        /// </summary>
        internal static string PSSyncOutputEventsFormatDuration {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsFormatDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.0}% complete; Remaining Time: {1}; Throughput: {2:0.0}Mbps.
        /// </summary>
        internal static string PSSyncOutputEventsLogProgress {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsLogProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string PSSyncOutputEventsLogProgressCompleteCompleted {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsLogProgressCompleteCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MD5 hash calculation is completed..
        /// </summary>
        internal static string PSSyncOutputEventsMD5HashCalculationFinished {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsMD5HashCalculationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range of the block is {0}, Length: {1}.
        /// </summary>
        internal static string PSSyncOutputEventsPrintBlockRange {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsPrintBlockRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Block Detection.
        /// </summary>
        internal static string PSSyncOutputEventsProgressEmptyBlockDetection {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsProgressEmptyBlockDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found existing page blob. Resuming upload....
        /// </summary>
        internal static string PSSyncOutputEventsResumingUpload {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsResumingUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network disruption occured, retrying..
        /// </summary>
        internal static string PSSyncOutputEventsRetryingAfterANetworkDisruption {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsRetryingAfterANetworkDisruption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed with exceptions:.
        /// </summary>
        internal static string PSSyncOutputEventsUploadFailedWithException {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsUploadFailedWithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        internal static string PSSyncOutputEventsUploading {
            get {
                return ResourceManager.GetString("PSSyncOutputEventsUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begin Operation: {0}.
        /// </summary>
        internal static string QuickVMBeginOperation {
            get {
                return ResourceManager.GetString("QuickVMBeginOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Operation: {0}.
        /// </summary>
        internal static string QuickVMCompletedOperation {
            get {
                return ResourceManager.GetString("QuickVMCompletedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Create Cloud Service.
        /// </summary>
        internal static string QuickVMCreateCloudService {
            get {
                return ResourceManager.GetString("QuickVMCreateCloudService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Create Deployment with VM {1}.
        /// </summary>
        internal static string QuickVMCreateDeploymentWithVM {
            get {
                return ResourceManager.GetString("QuickVMCreateDeploymentWithVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Create VM {1}.
        /// </summary>
        internal static string QuickVMCreateVM {
            get {
                return ResourceManager.GetString("QuickVMCreateVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Uploading Certificate: {1}.
        /// </summary>
        internal static string QuickVMUploadingCertificate {
            get {
                return ResourceManager.GetString("QuickVMUploadingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Uploading WinRMCertificate: {1}.
        /// </summary>
        internal static string QuickVMUploadingWinRMCertificate {
            get {
                return ResourceManager.GetString("QuickVMUploadingWinRMCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot and Reimage parameters are mutually exclusive..
        /// </summary>
        internal static string RebootAndReImageAreMutuallyExclusive {
            get {
                return ResourceManager.GetString("RebootAndReImageAreMutuallyExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot and Reimage parameters are mutually exclusive..
        /// </summary>
        internal static string RebootAndReImageExclusive {
            get {
                return ResourceManager.GetString("RebootAndReImageExclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot or Reimage parameters should be specified..
        /// </summary>
        internal static string RebootOrReImageAreMissing {
            get {
                return ResourceManager.GetString("RebootOrReImageAreMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot or Reimage parameters should be specified..
        /// </summary>
        internal static string RebootOrReImageMustBeSpecified {
            get {
                return ResourceManager.GetString("RebootOrReImageMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roleinstance cannot be found.
        /// </summary>
        internal static string RoleInstanceCanNotBeFound {
            get {
                return ResourceManager.GetString("RoleInstanceCanNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roleinstance cannot be found: {0}.
        /// </summary>
        internal static string RoleInstanceCanNotBeFoundWithName {
            get {
                return ResourceManager.GetString("RoleInstanceCanNotBeFoundWithName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InstanceStatus is {0}.
        /// </summary>
        internal static string RoleInstanceStatus {
            get {
                return ResourceManager.GetString("RoleInstanceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Service does not exist. Specify -Location or -Affinity group to create one..
        /// </summary>
        internal static string ServiceDoesNotExistSpecifyLocationOrAffinityGroup {
            get {
                return ResourceManager.GetString("ServiceDoesNotExistSpecifyLocationOrAffinityGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service already exists, AffinityGroup cannot be specified..
        /// </summary>
        internal static string ServiceExistsAffinityGroupCanNotBeSpecified {
            get {
                return ResourceManager.GetString("ServiceExistsAffinityGroupCanNotBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service already exists, Location cannot be specified..
        /// </summary>
        internal static string ServiceExistsLocationCanNotBeSpecified {
            get {
                return ResourceManager.GetString("ServiceExistsLocationCanNotBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot apply more than one extension in the same namespace and type: {0}..
        /// </summary>
        internal static string ServiceExtensionCannotApplyExtensionsInSameType {
            get {
                return ResourceManager.GetString("ServiceExtensionCannotApplyExtensionsInSameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deployment not found in service: {0} and slot: {1}..
        /// </summary>
        internal static string ServiceExtensionCannotFindDeployment {
            get {
                return ResourceManager.GetString("ServiceExtensionCannotFindDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role: {0} not found in deployment {1} of service {2}..
        /// </summary>
        internal static string ServiceExtensionCannotFindRole {
            get {
                return ResourceManager.GetString("ServiceExtensionCannotFindRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified role name cannot be empty or null..
        /// </summary>
        internal static string ServiceExtensionCannotFindRoleName {
            get {
                return ResourceManager.GetString("ServiceExtensionCannotFindRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find cloud service: {0}..
        /// </summary>
        internal static string ServiceExtensionCannotFindServiceName {
            get {
                return ResourceManager.GetString("ServiceExtensionCannotFindServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find storage account for the account name: {0}..
        /// </summary>
        internal static string ServiceExtensionCannotFindStorageAccount {
            get {
                return ResourceManager.GetString("ServiceExtensionCannotFindStorageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find storage keys for the account name: {0}..
        /// </summary>
        internal static string ServiceExtensionCannotFindStorageAccountKey {
            get {
                return ResourceManager.GetString("ServiceExtensionCannotFindStorageAccountKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find storage service for the account name: {0}..
        /// </summary>
        internal static string ServiceExtensionCannotFindStorageAccountName {
            get {
                return ResourceManager.GetString("ServiceExtensionCannotFindStorageAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existing {0}.{1} extensions enabled on given roles..
        /// </summary>
        internal static string ServiceExtensionNoExistingExtensionsEnabledOnRoles {
            get {
                return ResourceManager.GetString("ServiceExtensionNoExistingExtensionsEnabledOnRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing default {0} configuration for all roles from Cloud Service {1}..
        /// </summary>
        internal static string ServiceExtensionRemovingFromAllRoles {
            get {
                return ResourceManager.GetString("ServiceExtensionRemovingFromAllRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing {0} configuration for {1} from Cloud Service {2}..
        /// </summary>
        internal static string ServiceExtensionRemovingFromSpecificRoles {
            get {
                return ResourceManager.GetString("ServiceExtensionRemovingFromSpecificRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default {0} configuration exists applying default configuration to {1}..
        /// </summary>
        internal static string ServiceExtensionRemovingSpecificAndApplyingDefault {
            get {
                return ResourceManager.GetString("ServiceExtensionRemovingSpecificAndApplyingDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting default {0} configuration for all roles..
        /// </summary>
        internal static string ServiceExtensionSettingForDefaultRole {
            get {
                return ResourceManager.GetString("ServiceExtensionSettingForDefaultRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting {0} configuration for {1}..
        /// </summary>
        internal static string ServiceExtensionSettingForSpecificRole {
            get {
                return ResourceManager.GetString("ServiceExtensionSettingForSpecificRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Uploading Certificate: {1}.
        /// </summary>
        internal static string ServiceExtensionUploadingCertificate {
            get {
                return ResourceManager.GetString("ServiceExtensionUploadingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify -LinuxUser when creating Linux Virtual Machines.
        /// </summary>
        internal static string SpecifyLinuxUserWhenCreatingLinuxVMs {
            get {
                return ResourceManager.GetString("SpecifyLinuxUserWhenCreatingLinuxVMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Set-AzureSubscription and Select-AzureSubscription first..
        /// </summary>
        internal static string StorageCredentialsFactoryCurrentSubscriptionNotSet {
            get {
                return ResourceManager.GetString("StorageCredentialsFactoryCurrentSubscriptionNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading package to blob storage.
        /// </summary>
        internal static string UploadingPackage {
            get {
                return ResourceManager.GetString("UploadingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIP Swap is taking place between Staging and Production deployments.:{0}.
        /// </summary>
        internal static string VIPSwapBetweenStagingAndProduction {
            get {
                return ResourceManager.GetString("VIPSwapBetweenStagingAndProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory specified by the file path does not exist..
        /// </summary>
        internal static string VirtualNetworkConfigContextDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("VirtualNetworkConfigContextDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file path should be specified..
        /// </summary>
        internal static string VirtualNetworkConfigContextMissingFilePath {
            get {
                return ResourceManager.GetString("VirtualNetworkConfigContextMissingFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified virtual network name was not found: {0}.
        /// </summary>
        internal static string VirtualNetworkNameNotFound {
            get {
                return ResourceManager.GetString("VirtualNetworkNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory specified by the file path does not exist..
        /// </summary>
        internal static string VirtualNetworkSupportedDevicesContextDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("VirtualNetworkSupportedDevicesContextDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file path should be specified..
        /// </summary>
        internal static string VirtualNetworkSupportedDevicesContextMissingFilePath {
            get {
                return ResourceManager.GetString("VirtualNetworkSupportedDevicesContextMissingFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VM creation failed, VM status is &apos;{0}&apos;.
        /// </summary>
        internal static string VMCreationFailedWithVMStatus {
            get {
                return ResourceManager.GetString("VMCreationFailedWithVMStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Machine {0} is missing provisioning configuration.
        /// </summary>
        internal static string VMMissingProvisioningConfiguration {
            get {
                return ResourceManager.GetString("VMMissingProvisioningConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read properties for virtual machine: {0}. It may still be provisioning..
        /// </summary>
        internal static string VMPropertiesCanNotBeRead {
            get {
                return ResourceManager.GetString("VMPropertiesCanNotBeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Network Name may only be specified on the initial deployment. Specify Location or Affinity Group to create a new cloud service and deployment..
        /// </summary>
        internal static string VNetNameCanBeSpecifiedOnlyOnInitialDeployment {
            get {
                return ResourceManager.GetString("VNetNameCanBeSpecifiedOnlyOnInitialDeployment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VNetName, DnsSettings, DeploymentLabel or DeploymentName Name can only be specified on new deployments..
        /// </summary>
        internal static string VNetNameDnsSettingsDeploymentLabelDeploymentNameCanBeSpecifiedOnNewDeployments {
            get {
                return ResourceManager.GetString("VNetNameDnsSettingsDeploymentLabelDeploymentNameCanBeSpecifiedOnNewDeployments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VNetName or DnsSettings can only be specified on new deployments..
        /// </summary>
        internal static string VNetNameOrDnsSettingsCanOnlyBeSpecifiedOnNewDeployments {
            get {
                return ResourceManager.GetString("VNetNameOrDnsSettingsCanOnlyBeSpecifiedOnNewDeployments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VNetName is required when specifying DNS Settings..
        /// </summary>
        internal static string VNetNameRequiredWhenSpecifyingDNSSettings {
            get {
                return ResourceManager.GetString("VNetNameRequiredWhenSpecifyingDNSSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string WaitForUploadingPackage {
            get {
                return ResourceManager.GetString("WaitForUploadingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinRMCertificate needs to have an exportable private key..
        /// </summary>
        internal static string WinRMCertificateDoesNotHaveExportablePrivateKey {
            get {
                return ResourceManager.GetString("WinRMCertificateDoesNotHaveExportablePrivateKey", resourceCulture);
            }
        }
    }
}
