//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAzure.Management.Storage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAzure.Management.Storage.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob &apos;{0}&apos; in container &apos;{1}&apos; already exists..
        /// </summary>
        internal static string BlobAlreadyExists {
            get {
                return ResourceManager.GetString("BlobAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent : {0}% Speed : {1}.
        /// </summary>
        internal static string BlobDownloadingStatus {
            get {
                return ResourceManager.GetString("BlobDownloadingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob End Point: {0}.
        /// </summary>
        internal static string BlobEndPointTips {
            get {
                return ResourceManager.GetString("BlobEndPointTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find blob name or container name..
        /// </summary>
        internal static string BlobNameNotFound {
            get {
                return ResourceManager.GetString("BlobNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find blob &apos;{0}&apos; in container &apos;{1} &apos;.
        /// </summary>
        internal static string BlobNotFound {
            get {
                return ResourceManager.GetString("BlobNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob type mismatched, the current blob type of {0} is {1}..
        /// </summary>
        internal static string BlobTypeMismatch {
            get {
                return ResourceManager.GetString("BlobTypeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not send a directory to azure {0}..
        /// </summary>
        internal static string CannotSendDirectory {
            get {
                return ResourceManager.GetString("CannotSendDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to remove Container {0} ?.
        /// </summary>
        internal static string ConfirmRemoveContainer {
            get {
                return ResourceManager.GetString("ConfirmRemoveContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to Remove Azure Container.
        /// </summary>
        internal static string ConfirmRemoveContainerCaption {
            get {
                return ResourceManager.GetString("ConfirmRemoveContainerCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container &apos;{0}&apos; already exists!.
        /// </summary>
        internal static string ContainerAlreadyExists {
            get {
                return ResourceManager.GetString("ContainerAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find the container &apos;{0}&apos;.
        /// </summary>
        internal static string ContainerNotFound {
            get {
                return ResourceManager.GetString("ContainerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{0}&apos; doesn&apos;t exist..
        /// </summary>
        internal static string DirectoryNotExists {
            get {
                return ResourceManager.GetString("DirectoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot download the blob &apos;{0}&apos; in container &apos;{1}&apos; into local file &apos;{2}&apos;.  Error: {3}.
        /// </summary>
        internal static string DownloadBlobFailed {
            get {
                return ResourceManager.GetString("DownloadBlobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download blob {0} successful..
        /// </summary>
        internal static string DownloadBlobSuccessful {
            get {
                return ResourceManager.GetString("DownloadBlobSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; already exists..
        /// </summary>
        internal static string FileAlreadyExists {
            get {
                return ResourceManager.GetString("FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find the specified file. {0}.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent : {0}% Speed : {1} bytes/second.
        /// </summary>
        internal static string FileUploadingStatus {
            get {
                return ResourceManager.GetString("FileUploadingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply the account name with account key as the full azure credentials..
        /// </summary>
        internal static string IncompleteAccountInformation {
            get {
                return ResourceManager.GetString("IncompleteAccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid parameter combination, please see the command help..
        /// </summary>
        internal static string InvalidAccountParameterCombination {
            get {
                return ResourceManager.GetString("InvalidAccountParameterCombination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob name &apos;{0}&apos; is invalid.
        /// </summary>
        internal static string InValidBlobName {
            get {
                return ResourceManager.GetString("InValidBlobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICloudBlob &quot;{0}&quot; should contain container properties..
        /// </summary>
        internal static string InvalidBlobWithoutContainer {
            get {
                return ResourceManager.GetString("InvalidBlobWithoutContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Container name &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string InvalidContainerName {
            get {
                return ResourceManager.GetString("InvalidContainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ExpiryTime {0}..
        /// </summary>
        internal static string InvalidExpiryTime {
            get {
                return ResourceManager.GetString("InvalidExpiryTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name &quot;{0}&quot; is invalid..
        /// </summary>
        internal static string InvalidFileName {
            get {
                return ResourceManager.GetString("InvalidFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue name &apos;{0}&apos; is invalid.
        /// </summary>
        internal static string InvalidQueueName {
            get {
                return ResourceManager.GetString("InvalidQueueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lifetime of the shared access signature must be less than one hours..
        /// </summary>
        internal static string InvalidSASLifeTime {
            get {
                return ResourceManager.GetString("InvalidSASLifeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Start Time {0}..
        /// </summary>
        internal static string InvalidStartTime {
            get {
                return ResourceManager.GetString("InvalidStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name &apos;{0}&apos; is invalid.
        /// </summary>
        internal static string InvalidTableName {
            get {
                return ResourceManager.GetString("InvalidTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object &quot;{0}&quot; cannot be null..
        /// </summary>
        internal static string ObjectCannotBeNull {
            get {
                return ResourceManager.GetString("ObjectCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must supply only one permission for container..
        /// </summary>
        internal static string OnlyOnePermissionForContainer {
            get {
                return ResourceManager.GetString("OnlyOnePermissionForContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare to upload blob.
        /// </summary>
        internal static string PrepareUploadingBlob {
            get {
                return ResourceManager.GetString("PrepareUploadingBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue &apos;{0}&apos; already exists..
        /// </summary>
        internal static string QueueAlreadyExists {
            get {
                return ResourceManager.GetString("QueueAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find queue &apos;{0}&apos;..
        /// </summary>
        internal static string QueueNotFound {
            get {
                return ResourceManager.GetString("QueueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download bob {0} into {1}.
        /// </summary>
        internal static string ReceiveAzureBlobActivity {
            get {
                return ResourceManager.GetString("ReceiveAzureBlobActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove blob &apos;{0}&apos; in container &quot;{1}&quot; successfully.
        /// </summary>
        internal static string RemoveBlobSuccessfully {
            get {
                return ResourceManager.GetString("RemoveBlobSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remove operation of container {0} has been cancelled.
        /// </summary>
        internal static string RemoveContainerCancelled {
            get {
                return ResourceManager.GetString("RemoveContainerCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove container &apos;{0}&apos; successfully.
        /// </summary>
        internal static string RemoveContainerSuccessfully {
            get {
                return ResourceManager.GetString("RemoveContainerSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remove operation of queue {0} has been cancelled.
        /// </summary>
        internal static string RemoveQueueCancelled {
            get {
                return ResourceManager.GetString("RemoveQueueCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove queue &apos;{0}&apos; successfully..
        /// </summary>
        internal static string RemoveQueueSuccessfully {
            get {
                return ResourceManager.GetString("RemoveQueueSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remove operation of table {0} has been cancelled.
        /// </summary>
        internal static string RemoveTableCancelled {
            get {
                return ResourceManager.GetString("RemoveTableCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove table &apos;{0}&apos; successfully.
        /// </summary>
        internal static string RemoveTableSuccessfully {
            get {
                return ResourceManager.GetString("RemoveTableSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file {0} into blob {1} in container {2}..
        /// </summary>
        internal static string SendAzureBlobActivity {
            get {
                return ResourceManager.GetString("SendAzureBlobActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload local file {0} into blob {1} cancelled..
        /// </summary>
        internal static string SendAzureBlobCancelled {
            get {
                return ResourceManager.GetString("SendAzureBlobCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start to Downloading Blob {0}.
        /// </summary>
        internal static string StartDownloadBlob {
            get {
                return ResourceManager.GetString("StartDownloadBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start to Upload {0} into Blob {1}.
        /// </summary>
        internal static string StartUploadFile {
            get {
                return ResourceManager.GetString("StartUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find your azure storage credential..
        /// </summary>
        internal static string StorageCredentialsNotFound {
            get {
                return ResourceManager.GetString("StorageCredentialsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table &apos;{0}&apos; already exists..
        /// </summary>
        internal static string TableAlreadyExists {
            get {
                return ResourceManager.GetString("TableAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not find table &apos;{0}&apos;..
        /// </summary>
        internal static string TableNotFound {
            get {
                return ResourceManager.GetString("TableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Blob.
        /// </summary>
        internal static string UnknownBlob {
            get {
                return ResourceManager.GetString("UnknownBlob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not upload local file to azure blob. {0}.
        /// </summary>
        internal static string Upload2BlobFailed {
            get {
                return ResourceManager.GetString("Upload2BlobFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file {0} failed,  Error : {1}.
        /// </summary>
        internal static string UploadFileFailed {
            get {
                return ResourceManager.GetString("UploadFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file {0} successfully..
        /// </summary>
        internal static string UploadFileSuccessfully {
            get {
                return ResourceManager.GetString("UploadFileSuccessfully", resourceCulture);
            }
        }
    }
}
