//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAzure.ServiceManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAzure.ServiceManagement.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access Service property on a client that has already been cleaned up..
        /// </summary>
        internal static string AccessDisposedClientError {
            get {
                return ResourceManager.GetString("AccessDisposedClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be null..
        /// </summary>
        internal static string ArgumentNullError {
            get {
                return ResourceManager.GetString("ArgumentNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not set outgoing request headers..
        /// </summary>
        internal static string CouldNotSetRequestHeaderError {
            get {
                return ResourceManager.GetString("CouldNotSetRequestHeaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot initialize a client that has already been cleaned up..
        /// </summary>
        internal static string InitDisposedClientError {
            get {
                return ResourceManager.GetString("InitDisposedClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;NONE&gt;.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;An exception occurred when calling the ServiceManagement API. HTTP Status Code: {0}. Service Management Error Code: {1}. Message: {2}. Operation Tracking ID: {3}.&quot;.
        /// </summary>
        internal static string ServiceManagementClientExceptionStringFormat {
            get {
                return ResourceManager.GetString("ServiceManagementClientExceptionStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The x-ms-requestid {0} did not complete after {1} seconds..
        /// </summary>
        internal static string ServiceManagementTimeoutError {
            get {
                return ResourceManager.GetString("ServiceManagementTimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty..
        /// </summary>
        internal static string StringArgumentEmptyError {
            get {
                return ResourceManager.GetString("StringArgumentEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation with ID {0} failed with unknown HTTP Status Code: {1}..
        /// </summary>
        internal static string UnknownHttpStatusError {
            get {
                return ResourceManager.GetString("UnknownHttpStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Management operation with ID {0} returned unrecognized status: {1}..
        /// </summary>
        internal static string UnknownOperationStatus {
            get {
                return ResourceManager.GetString("UnknownOperationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a recognized trace event type..
        /// </summary>
        internal static string UnrecognizedTraceType {
            get {
                return ResourceManager.GetString("UnrecognizedTraceType", resourceCulture);
            }
        }
    }
}
