//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name: ServerContextInternal.cs
// Generation date: 8/17/2012 11:39:09 PM
namespace Microsoft.WindowsAzure.Management.SqlDatabase.Services.Server
{
    
    /// <summary>
    /// There are no comments for ServerContextInternal in the schema.
    /// </summary>
    public abstract partial class ServerContextInternal : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new ServerContextInternal object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public ServerContextInternal(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Servers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Server> Servers
        {
            get
            {
                if ((this._Servers == null))
                {
                    this._Servers = base.CreateQuery<Server>("Servers");
                }
                return this._Servers;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Server> _Servers;
        /// <summary>
        /// There are no comments for Databases in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Database> Databases
        {
            get
            {
                if ((this._Databases == null))
                {
                    this._Databases = base.CreateQuery<Database>("Databases");
                }
                return this._Databases;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Database> _Databases;
        /// <summary>
        /// There are no comments for Operations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Operation> Operations
        {
            get
            {
                if ((this._Operations == null))
                {
                    this._Operations = base.CreateQuery<Operation>("Operations");
                }
                return this._Operations;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Operation> _Operations;
        /// <summary>
        /// There are no comments for OperationDetails in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<OperationDetail> OperationDetails
        {
            get
            {
                if ((this._OperationDetails == null))
                {
                    this._OperationDetails = base.CreateQuery<OperationDetail>("OperationDetails");
                }
                return this._OperationDetails;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<OperationDetail> _OperationDetails;
        /// <summary>
        /// There are no comments for CreateDatabaseFromDacPacOperations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CreateDatabaseFromDacPacOperation> CreateDatabaseFromDacPacOperations
        {
            get
            {
                if ((this._CreateDatabaseFromDacPacOperations == null))
                {
                    this._CreateDatabaseFromDacPacOperations = base.CreateQuery<CreateDatabaseFromDacPacOperation>("CreateDatabaseFromDacPacOperations");
                }
                return this._CreateDatabaseFromDacPacOperations;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CreateDatabaseFromDacPacOperation> _CreateDatabaseFromDacPacOperations;
        /// <summary>
        /// There are no comments for ExtractDacPacOperations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ExtractDacPacOperation> ExtractDacPacOperations
        {
            get
            {
                if ((this._ExtractDacPacOperations == null))
                {
                    this._ExtractDacPacOperations = base.CreateQuery<ExtractDacPacOperation>("ExtractDacPacOperations");
                }
                return this._ExtractDacPacOperations;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ExtractDacPacOperation> _ExtractDacPacOperations;
        /// <summary>
        /// There are no comments for UpgradeDatabaseFromDacPacOperations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<UpgradeDatabaseFromDacPacOperation> UpgradeDatabaseFromDacPacOperations
        {
            get
            {
                if ((this._UpgradeDatabaseFromDacPacOperations == null))
                {
                    this._UpgradeDatabaseFromDacPacOperations = base.CreateQuery<UpgradeDatabaseFromDacPacOperation>("UpgradeDatabaseFromDacPacOperations");
                }
                return this._UpgradeDatabaseFromDacPacOperations;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<UpgradeDatabaseFromDacPacOperation> _UpgradeDatabaseFromDacPacOperations;
        /// <summary>
        /// There are no comments for ViewDatabaseChangesOperations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ViewDatabaseChangesOperation> ViewDatabaseChangesOperations
        {
            get
            {
                if ((this._ViewDatabaseChangesOperations == null))
                {
                    this._ViewDatabaseChangesOperations = base.CreateQuery<ViewDatabaseChangesOperation>("ViewDatabaseChangesOperations");
                }
                return this._ViewDatabaseChangesOperations;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ViewDatabaseChangesOperation> _ViewDatabaseChangesOperations;
        /// <summary>
        /// There are no comments for ViewUpgradePlanOperations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ViewUpgradePlanOperation> ViewUpgradePlanOperations
        {
            get
            {
                if ((this._ViewUpgradePlanOperations == null))
                {
                    this._ViewUpgradePlanOperations = base.CreateQuery<ViewUpgradePlanOperation>("ViewUpgradePlanOperations");
                }
                return this._ViewUpgradePlanOperations;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ViewUpgradePlanOperation> _ViewUpgradePlanOperations;
        /// <summary>
        /// There are no comments for FirewallRules in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<FirewallRule> FirewallRules
        {
            get
            {
                if ((this._FirewallRules == null))
                {
                    this._FirewallRules = base.CreateQuery<FirewallRule>("FirewallRules");
                }
                return this._FirewallRules;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<FirewallRule> _FirewallRules;
        /// <summary>
        /// There are no comments for Servers in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToServers(Server server)
        {
            base.AddObject("Servers", server);
        }
        /// <summary>
        /// There are no comments for Databases in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDatabases(Database database)
        {
            base.AddObject("Databases", database);
        }
        /// <summary>
        /// There are no comments for Operations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToOperations(Operation operation)
        {
            base.AddObject("Operations", operation);
        }
        /// <summary>
        /// There are no comments for OperationDetails in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToOperationDetails(OperationDetail operationDetail)
        {
            base.AddObject("OperationDetails", operationDetail);
        }
        /// <summary>
        /// There are no comments for CreateDatabaseFromDacPacOperations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCreateDatabaseFromDacPacOperations(CreateDatabaseFromDacPacOperation createDatabaseFromDacPacOperation)
        {
            base.AddObject("CreateDatabaseFromDacPacOperations", createDatabaseFromDacPacOperation);
        }
        /// <summary>
        /// There are no comments for ExtractDacPacOperations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToExtractDacPacOperations(ExtractDacPacOperation extractDacPacOperation)
        {
            base.AddObject("ExtractDacPacOperations", extractDacPacOperation);
        }
        /// <summary>
        /// There are no comments for UpgradeDatabaseFromDacPacOperations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUpgradeDatabaseFromDacPacOperations(UpgradeDatabaseFromDacPacOperation upgradeDatabaseFromDacPacOperation)
        {
            base.AddObject("UpgradeDatabaseFromDacPacOperations", upgradeDatabaseFromDacPacOperation);
        }
        /// <summary>
        /// There are no comments for ViewDatabaseChangesOperations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToViewDatabaseChangesOperations(ViewDatabaseChangesOperation viewDatabaseChangesOperation)
        {
            base.AddObject("ViewDatabaseChangesOperations", viewDatabaseChangesOperation);
        }
        /// <summary>
        /// There are no comments for ViewUpgradePlanOperations in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToViewUpgradePlanOperations(ViewUpgradePlanOperation viewUpgradePlanOperation)
        {
            base.AddObject("ViewUpgradePlanOperations", viewUpgradePlanOperation);
        }
        /// <summary>
        /// There are no comments for FirewallRules in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFirewallRules(FirewallRule firewallRule)
        {
            base.AddObject("FirewallRules", firewallRule);
        }
    }
    /// <summary>
    /// There are no comments for Microsoft.SqlServer.Management.Server.Domain.Server in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Name
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Name")]
    public partial class Server
    {
        /// <summary>
        /// Create a new Server object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Server CreateServer(string name)
        {
            Server server = new Server();
            server.Name = name;
            return server;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Databases in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<Database> Databases
        {
            get
            {
                return this._Databases;
            }
            set
            {
                if ((value != null))
                {
                    this._Databases = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<Database> _Databases = new global::System.Collections.ObjectModel.Collection<Database>();
    }
    /// <summary>
    /// There are no comments for Microsoft.SqlServer.Management.Server.Domain.Database in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Database
    {
        /// <summary>
        /// Create a new Database object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="creationDate">Initial value of CreationDate.</param>
        /// <param name="isSystemObject">Initial value of IsSystemObject.</param>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="sizeMB">Initial value of SizeMB.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Database CreateDatabase(int ID, global::System.DateTime creationDate, bool isSystemObject, int status, decimal sizeMB)
        {
            Database database = new Database();
            database.Id = ID;
            database.CreationDate = creationDate;
            database.IsSystemObject = isSystemObject;
            database.Status = status;
            database.SizeMB = sizeMB;
            return database;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Edition in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Edition
        {
            get
            {
                return this._Edition;
            }
            set
            {
                this.OnEditionChanging(value);
                this._Edition = value;
                this.OnEditionChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Edition;
        partial void OnEditionChanging(string value);
        partial void OnEditionChanged();
        /// <summary>
        /// There are no comments for Property MaxSizeGB in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> MaxSizeGB
        {
            get
            {
                return this._MaxSizeGB;
            }
            set
            {
                this.OnMaxSizeGBChanging(value);
                this._MaxSizeGB = value;
                this.OnMaxSizeGBChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _MaxSizeGB;
        partial void OnMaxSizeGBChanging(global::System.Nullable<int> value);
        partial void OnMaxSizeGBChanged();
        /// <summary>
        /// There are no comments for Property CollationName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CollationName
        {
            get
            {
                return this._CollationName;
            }
            set
            {
                this.OnCollationNameChanging(value);
                this._CollationName = value;
                this.OnCollationNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CollationName;
        partial void OnCollationNameChanging(string value);
        partial void OnCollationNameChanged();
        /// <summary>
        /// There are no comments for Property CreationDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreationDate
        {
            get
            {
                return this._CreationDate;
            }
            set
            {
                this.OnCreationDateChanging(value);
                this._CreationDate = value;
                this.OnCreationDateChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreationDate;
        partial void OnCreationDateChanging(global::System.DateTime value);
        partial void OnCreationDateChanged();
        /// <summary>
        /// There are no comments for Property IsSystemObject in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsSystemObject
        {
            get
            {
                return this._IsSystemObject;
            }
            set
            {
                this.OnIsSystemObjectChanging(value);
                this._IsSystemObject = value;
                this.OnIsSystemObjectChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsSystemObject;
        partial void OnIsSystemObjectChanging(bool value);
        partial void OnIsSystemObjectChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this._Status = value;
                this.OnStatusChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Status;
        partial void OnStatusChanging(int value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property IsFederationRoot in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> IsFederationRoot
        {
            get
            {
                return this._IsFederationRoot;
            }
            set
            {
                this.OnIsFederationRootChanging(value);
                this._IsFederationRoot = value;
                this.OnIsFederationRootChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _IsFederationRoot;
        partial void OnIsFederationRootChanging(global::System.Nullable<bool> value);
        partial void OnIsFederationRootChanged();
        /// <summary>
        /// There are no comments for Property SizeMB in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal SizeMB
        {
            get
            {
                return this._SizeMB;
            }
            set
            {
                this.OnSizeMBChanging(value);
                this._SizeMB = value;
                this.OnSizeMBChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _SizeMB;
        partial void OnSizeMBChanging(decimal value);
        partial void OnSizeMBChanged();
        /// <summary>
        /// There are no comments for Property IsRecursiveTriggersOn in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> IsRecursiveTriggersOn
        {
            get
            {
                return this._IsRecursiveTriggersOn;
            }
            set
            {
                this.OnIsRecursiveTriggersOnChanging(value);
                this._IsRecursiveTriggersOn = value;
                this.OnIsRecursiveTriggersOnChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _IsRecursiveTriggersOn;
        partial void OnIsRecursiveTriggersOnChanging(global::System.Nullable<bool> value);
        partial void OnIsRecursiveTriggersOnChanged();
        /// <summary>
        /// There are no comments for Server in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Server Server
        {
            get
            {
                return this._Server;
            }
            set
            {
                this._Server = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Server _Server;
    }
    /// <summary>
    /// There are no comments for Microsoft.SqlServer.Management.Server.Domain.Operation in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ActionId
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ActionId")]
    public partial class Operation
    {
        /// <summary>
        /// Create a new Operation object.
        /// </summary>
        /// <param name="dateCreated">Initial value of DateCreated.</param>
        /// <param name="dateModified">Initial value of DateModified.</param>
        /// <param name="actionId">Initial value of ActionId.</param>
        /// <param name="completedSteps">Initial value of CompletedSteps.</param>
        /// <param name="totalSteps">Initial value of TotalSteps.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Operation CreateOperation(global::System.DateTime dateCreated, global::System.DateTime dateModified, int actionId, int completedSteps, int totalSteps)
        {
            Operation operation = new Operation();
            operation.DateCreated = dateCreated;
            operation.DateModified = dateModified;
            operation.ActionId = actionId;
            operation.CompletedSteps = completedSteps;
            operation.TotalSteps = totalSteps;
            return operation;
        }
        /// <summary>
        /// There are no comments for Property ActionTypeName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ActionTypeName
        {
            get
            {
                return this._ActionTypeName;
            }
            set
            {
                this.OnActionTypeNameChanging(value);
                this._ActionTypeName = value;
                this.OnActionTypeNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ActionTypeName;
        partial void OnActionTypeNameChanging(string value);
        partial void OnActionTypeNameChanged();
        /// <summary>
        /// There are no comments for Property ActionStatusName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ActionStatusName
        {
            get
            {
                return this._ActionStatusName;
            }
            set
            {
                this.OnActionStatusNameChanging(value);
                this._ActionStatusName = value;
                this.OnActionStatusNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ActionStatusName;
        partial void OnActionStatusNameChanging(string value);
        partial void OnActionStatusNameChanged();
        /// <summary>
        /// There are no comments for Property DacDatabaseName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DacDatabaseName
        {
            get
            {
                return this._DacDatabaseName;
            }
            set
            {
                this.OnDacDatabaseNameChanging(value);
                this._DacDatabaseName = value;
                this.OnDacDatabaseNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DacDatabaseName;
        partial void OnDacDatabaseNameChanging(string value);
        partial void OnDacDatabaseNameChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property DateCreated in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this.OnDateCreatedChanging(value);
                this._DateCreated = value;
                this.OnDateCreatedChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
        /// <summary>
        /// There are no comments for Property DateModified in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime DateModified
        {
            get
            {
                return this._DateModified;
            }
            set
            {
                this.OnDateModifiedChanging(value);
                this._DateModified = value;
                this.OnDateModifiedChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _DateModified;
        partial void OnDateModifiedChanging(global::System.DateTime value);
        partial void OnDateModifiedChanged();
        /// <summary>
        /// There are no comments for Property Comments in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                this.OnCommentsChanging(value);
                this._Comments = value;
                this.OnCommentsChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comments;
        partial void OnCommentsChanging(string value);
        partial void OnCommentsChanged();
        /// <summary>
        /// There are no comments for Property Error in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Error
        {
            get
            {
                return this._Error;
            }
            set
            {
                this.OnErrorChanging(value);
                this._Error = value;
                this.OnErrorChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Error;
        partial void OnErrorChanging(string value);
        partial void OnErrorChanged();
        /// <summary>
        /// There are no comments for Property ActionId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ActionId
        {
            get
            {
                return this._ActionId;
            }
            set
            {
                this.OnActionIdChanging(value);
                this._ActionId = value;
                this.OnActionIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ActionId;
        partial void OnActionIdChanging(int value);
        partial void OnActionIdChanged();
        /// <summary>
        /// There are no comments for Property CompletedSteps in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CompletedSteps
        {
            get
            {
                return this._CompletedSteps;
            }
            set
            {
                this.OnCompletedStepsChanging(value);
                this._CompletedSteps = value;
                this.OnCompletedStepsChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CompletedSteps;
        partial void OnCompletedStepsChanging(int value);
        partial void OnCompletedStepsChanged();
        /// <summary>
        /// There are no comments for Property TotalSteps in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int TotalSteps
        {
            get
            {
                return this._TotalSteps;
            }
            set
            {
                this.OnTotalStepsChanging(value);
                this._TotalSteps = value;
                this.OnTotalStepsChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _TotalSteps;
        partial void OnTotalStepsChanging(int value);
        partial void OnTotalStepsChanged();
        /// <summary>
        /// There are no comments for Property DacObjectTypeName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DacObjectTypeName
        {
            get
            {
                return this._DacObjectTypeName;
            }
            set
            {
                this.OnDacObjectTypeNameChanging(value);
                this._DacObjectTypeName = value;
                this.OnDacObjectTypeNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DacObjectTypeName;
        partial void OnDacObjectTypeNameChanging(string value);
        partial void OnDacObjectTypeNameChanged();
        /// <summary>
        /// There are no comments for OperationDetails in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Collections.ObjectModel.Collection<OperationDetail> OperationDetails
        {
            get
            {
                return this._OperationDetails;
            }
            set
            {
                if ((value != null))
                {
                    this._OperationDetails = value;
                }
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Collections.ObjectModel.Collection<OperationDetail> _OperationDetails = new global::System.Collections.ObjectModel.Collection<OperationDetail>();
    }
    /// <summary>
    /// There are no comments for Microsoft.SqlServer.Management.Server.Domain.OperationDetail in the schema.
    /// </summary>
    /// <KeyProperties>
    /// EntityId
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("EntityId")]
    public partial class OperationDetail
    {
        /// <summary>
        /// Create a new OperationDetail object.
        /// </summary>
        /// <param name="dateCreated">Initial value of DateCreated.</param>
        /// <param name="dateModified">Initial value of DateModified.</param>
        /// <param name="sequenceId">Initial value of SequenceId.</param>
        /// <param name="entityId">Initial value of EntityId.</param>
        /// <param name="actionId">Initial value of ActionId.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static OperationDetail CreateOperationDetail(global::System.DateTime dateCreated, global::System.DateTime dateModified, int sequenceId, string entityId, int actionId)
        {
            OperationDetail operationDetail = new OperationDetail();
            operationDetail.DateCreated = dateCreated;
            operationDetail.DateModified = dateModified;
            operationDetail.SequenceId = sequenceId;
            operationDetail.EntityId = entityId;
            operationDetail.ActionId = actionId;
            return operationDetail;
        }
        /// <summary>
        /// There are no comments for Property ActionTypeName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ActionTypeName
        {
            get
            {
                return this._ActionTypeName;
            }
            set
            {
                this.OnActionTypeNameChanging(value);
                this._ActionTypeName = value;
                this.OnActionTypeNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ActionTypeName;
        partial void OnActionTypeNameChanging(string value);
        partial void OnActionTypeNameChanged();
        /// <summary>
        /// There are no comments for Property ActionStatusName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ActionStatusName
        {
            get
            {
                return this._ActionStatusName;
            }
            set
            {
                this.OnActionStatusNameChanging(value);
                this._ActionStatusName = value;
                this.OnActionStatusNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ActionStatusName;
        partial void OnActionStatusNameChanging(string value);
        partial void OnActionStatusNameChanged();
        /// <summary>
        /// There are no comments for Property DacDatabaseName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DacDatabaseName
        {
            get
            {
                return this._DacDatabaseName;
            }
            set
            {
                this.OnDacDatabaseNameChanging(value);
                this._DacDatabaseName = value;
                this.OnDacDatabaseNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DacDatabaseName;
        partial void OnDacDatabaseNameChanging(string value);
        partial void OnDacDatabaseNameChanged();
        /// <summary>
        /// There are no comments for Property CreatedBy in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CreatedBy
        {
            get
            {
                return this._CreatedBy;
            }
            set
            {
                this.OnCreatedByChanging(value);
                this._CreatedBy = value;
                this.OnCreatedByChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CreatedBy;
        partial void OnCreatedByChanging(string value);
        partial void OnCreatedByChanged();
        /// <summary>
        /// There are no comments for Property DateCreated in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime DateCreated
        {
            get
            {
                return this._DateCreated;
            }
            set
            {
                this.OnDateCreatedChanging(value);
                this._DateCreated = value;
                this.OnDateCreatedChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _DateCreated;
        partial void OnDateCreatedChanging(global::System.DateTime value);
        partial void OnDateCreatedChanged();
        /// <summary>
        /// There are no comments for Property DateModified in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime DateModified
        {
            get
            {
                return this._DateModified;
            }
            set
            {
                this.OnDateModifiedChanging(value);
                this._DateModified = value;
                this.OnDateModifiedChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _DateModified;
        partial void OnDateModifiedChanging(global::System.DateTime value);
        partial void OnDateModifiedChanged();
        /// <summary>
        /// There are no comments for Property Comments in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Comments
        {
            get
            {
                return this._Comments;
            }
            set
            {
                this.OnCommentsChanging(value);
                this._Comments = value;
                this.OnCommentsChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Comments;
        partial void OnCommentsChanging(string value);
        partial void OnCommentsChanged();
        /// <summary>
        /// There are no comments for Property Error in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Error
        {
            get
            {
                return this._Error;
            }
            set
            {
                this.OnErrorChanging(value);
                this._Error = value;
                this.OnErrorChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Error;
        partial void OnErrorChanging(string value);
        partial void OnErrorChanged();
        /// <summary>
        /// There are no comments for Property SequenceId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SequenceId
        {
            get
            {
                return this._SequenceId;
            }
            set
            {
                this.OnSequenceIdChanging(value);
                this._SequenceId = value;
                this.OnSequenceIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SequenceId;
        partial void OnSequenceIdChanging(int value);
        partial void OnSequenceIdChanged();
        /// <summary>
        /// There are no comments for Property EntityId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EntityId
        {
            get
            {
                return this._EntityId;
            }
            set
            {
                this.OnEntityIdChanging(value);
                this._EntityId = value;
                this.OnEntityIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EntityId;
        partial void OnEntityIdChanging(string value);
        partial void OnEntityIdChanged();
        /// <summary>
        /// There are no comments for Property ActionId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ActionId
        {
            get
            {
                return this._ActionId;
            }
            set
            {
                this.OnActionIdChanging(value);
                this._ActionId = value;
                this.OnActionIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ActionId;
        partial void OnActionIdChanging(int value);
        partial void OnActionIdChanged();
        /// <summary>
        /// There are no comments for Property DacObjectTypeName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DacObjectTypeName
        {
            get
            {
                return this._DacObjectTypeName;
            }
            set
            {
                this.OnDacObjectTypeNameChanging(value);
                this._DacObjectTypeName = value;
                this.OnDacObjectTypeNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DacObjectTypeName;
        partial void OnDacObjectTypeNameChanging(string value);
        partial void OnDacObjectTypeNameChanged();
        /// <summary>
        /// There are no comments for Operation in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Operation Operation
        {
            get
            {
                return this._Operation;
            }
            set
            {
                this._Operation = value;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Operation _Operation;
    }
    /// <summary>
    /// There are no comments for Microsoft.SqlServer.Management.Server.Domain.CreateDatabaseFromDacPacOperation in the schema.
    /// </summary>
    /// <KeyProperties>
    /// OperationGuid
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("OperationGuid")]
    public partial class CreateDatabaseFromDacPacOperation
    {
        /// <summary>
        /// Create a new CreateDatabaseFromDacPacOperation object.
        /// </summary>
        /// <param name="operationGuid">Initial value of OperationGuid.</param>
        /// <param name="operationId">Initial value of OperationId.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CreateDatabaseFromDacPacOperation CreateCreateDatabaseFromDacPacOperation(global::System.Guid operationGuid, int operationId)
        {
            CreateDatabaseFromDacPacOperation createDatabaseFromDacPacOperation = new CreateDatabaseFromDacPacOperation();
            createDatabaseFromDacPacOperation.OperationGuid = operationGuid;
            createDatabaseFromDacPacOperation.OperationId = operationId;
            return createDatabaseFromDacPacOperation;
        }
        /// <summary>
        /// There are no comments for Property OperationGuid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid OperationGuid
        {
            get
            {
                return this._OperationGuid;
            }
            set
            {
                this.OnOperationGuidChanging(value);
                this._OperationGuid = value;
                this.OnOperationGuidChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _OperationGuid;
        partial void OnOperationGuidChanging(global::System.Guid value);
        partial void OnOperationGuidChanged();
        /// <summary>
        /// There are no comments for Property DatabaseName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DatabaseName
        {
            get
            {
                return this._DatabaseName;
            }
            set
            {
                this.OnDatabaseNameChanging(value);
                this._DatabaseName = value;
                this.OnDatabaseNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DatabaseName;
        partial void OnDatabaseNameChanging(string value);
        partial void OnDatabaseNameChanged();
        /// <summary>
        /// There are no comments for Property Edition in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Edition
        {
            get
            {
                return this._Edition;
            }
            set
            {
                this.OnEditionChanging(value);
                this._Edition = value;
                this.OnEditionChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Edition;
        partial void OnEditionChanging(string value);
        partial void OnEditionChanged();
        /// <summary>
        /// There are no comments for Property MaxSizeGB in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> MaxSizeGB
        {
            get
            {
                return this._MaxSizeGB;
            }
            set
            {
                this.OnMaxSizeGBChanging(value);
                this._MaxSizeGB = value;
                this.OnMaxSizeGBChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _MaxSizeGB;
        partial void OnMaxSizeGBChanging(global::System.Nullable<int> value);
        partial void OnMaxSizeGBChanged();
        /// <summary>
        /// There are no comments for Property OperationId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int OperationId
        {
            get
            {
                return this._OperationId;
            }
            set
            {
                this.OnOperationIdChanging(value);
                this._OperationId = value;
                this.OnOperationIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _OperationId;
        partial void OnOperationIdChanging(int value);
        partial void OnOperationIdChanged();
        /// <summary>
        /// There are no comments for Property DacPac in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] DacPac
        {
            get
            {
                if ((this._DacPac != null))
                {
                    return ((byte[])(this._DacPac.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnDacPacChanging(value);
                this._DacPac = value;
                this.OnDacPacChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _DacPac;
        partial void OnDacPacChanging(byte[] value);
        partial void OnDacPacChanged();
    }
    /// <summary>
    /// There are no comments for Microsoft.SqlServer.Management.Server.Domain.ExtractDacPacOperation in the schema.
    /// </summary>
    /// <KeyProperties>
    /// OperationGuid
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("OperationGuid")]
    public partial class ExtractDacPacOperation
    {
        /// <summary>
        /// Create a new ExtractDacPacOperation object.
        /// </summary>
        /// <param name="operationGuid">Initial value of OperationGuid.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ExtractDacPacOperation CreateExtractDacPacOperation(global::System.Guid operationGuid)
        {
            ExtractDacPacOperation extractDacPacOperation = new ExtractDacPacOperation();
            extractDacPacOperation.OperationGuid = operationGuid;
            return extractDacPacOperation;
        }
        /// <summary>
        /// There are no comments for Property OperationGuid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid OperationGuid
        {
            get
            {
                return this._OperationGuid;
            }
            set
            {
                this.OnOperationGuidChanging(value);
                this._OperationGuid = value;
                this.OnOperationGuidChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _OperationGuid;
        partial void OnOperationGuidChanging(global::System.Guid value);
        partial void OnOperationGuidChanged();
        /// <summary>
        /// There are no comments for Property DatabaseName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DatabaseName
        {
            get
            {
                return this._DatabaseName;
            }
            set
            {
                this.OnDatabaseNameChanging(value);
                this._DatabaseName = value;
                this.OnDatabaseNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DatabaseName;
        partial void OnDatabaseNameChanging(string value);
        partial void OnDatabaseNameChanged();
        /// <summary>
        /// There are no comments for Property DacTypeName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DacTypeName
        {
            get
            {
                return this._DacTypeName;
            }
            set
            {
                this.OnDacTypeNameChanging(value);
                this._DacTypeName = value;
                this.OnDacTypeNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DacTypeName;
        partial void OnDacTypeNameChanging(string value);
        partial void OnDacTypeNameChanged();
        /// <summary>
        /// There are no comments for Property Version in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this._Version = value;
                this.OnVersionChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Version;
        partial void OnVersionChanging(string value);
        partial void OnVersionChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property DacPac in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] DacPac
        {
            get
            {
                if ((this._DacPac != null))
                {
                    return ((byte[])(this._DacPac.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnDacPacChanging(value);
                this._DacPac = value;
                this.OnDacPacChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _DacPac;
        partial void OnDacPacChanging(byte[] value);
        partial void OnDacPacChanged();
    }
    /// <summary>
    /// There are no comments for Microsoft.SqlServer.Management.Server.Domain.UpgradeDatabaseFromDacPacOperation in the schema.
    /// </summary>
    /// <KeyProperties>
    /// OperationGuid
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("OperationGuid")]
    public partial class UpgradeDatabaseFromDacPacOperation
    {
        /// <summary>
        /// Create a new UpgradeDatabaseFromDacPacOperation object.
        /// </summary>
        /// <param name="operationGuid">Initial value of OperationGuid.</param>
        /// <param name="operationId">Initial value of OperationId.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static UpgradeDatabaseFromDacPacOperation CreateUpgradeDatabaseFromDacPacOperation(global::System.Guid operationGuid, int operationId)
        {
            UpgradeDatabaseFromDacPacOperation upgradeDatabaseFromDacPacOperation = new UpgradeDatabaseFromDacPacOperation();
            upgradeDatabaseFromDacPacOperation.OperationGuid = operationGuid;
            upgradeDatabaseFromDacPacOperation.OperationId = operationId;
            return upgradeDatabaseFromDacPacOperation;
        }
        /// <summary>
        /// There are no comments for Property OperationGuid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid OperationGuid
        {
            get
            {
                return this._OperationGuid;
            }
            set
            {
                this.OnOperationGuidChanging(value);
                this._OperationGuid = value;
                this.OnOperationGuidChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _OperationGuid;
        partial void OnOperationGuidChanging(global::System.Guid value);
        partial void OnOperationGuidChanged();
        /// <summary>
        /// There are no comments for Property DatabaseName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DatabaseName
        {
            get
            {
                return this._DatabaseName;
            }
            set
            {
                this.OnDatabaseNameChanging(value);
                this._DatabaseName = value;
                this.OnDatabaseNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DatabaseName;
        partial void OnDatabaseNameChanging(string value);
        partial void OnDatabaseNameChanged();
        /// <summary>
        /// There are no comments for Property DacPac in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] DacPac
        {
            get
            {
                if ((this._DacPac != null))
                {
                    return ((byte[])(this._DacPac.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnDacPacChanging(value);
                this._DacPac = value;
                this.OnDacPacChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _DacPac;
        partial void OnDacPacChanging(byte[] value);
        partial void OnDacPacChanged();
        /// <summary>
        /// There are no comments for Property RollbackOnFailure in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> RollbackOnFailure
        {
            get
            {
                return this._RollbackOnFailure;
            }
            set
            {
                this.OnRollbackOnFailureChanging(value);
                this._RollbackOnFailure = value;
                this.OnRollbackOnFailureChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _RollbackOnFailure;
        partial void OnRollbackOnFailureChanging(global::System.Nullable<bool> value);
        partial void OnRollbackOnFailureChanged();
        /// <summary>
        /// There are no comments for Property OperationId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int OperationId
        {
            get
            {
                return this._OperationId;
            }
            set
            {
                this.OnOperationIdChanging(value);
                this._OperationId = value;
                this.OnOperationIdChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _OperationId;
        partial void OnOperationIdChanging(int value);
        partial void OnOperationIdChanged();
    }
    /// <summary>
    /// There are no comments for Microsoft.SqlServer.Management.Server.Domain.ViewDatabaseChangesOperation in the schema.
    /// </summary>
    /// <KeyProperties>
    /// OperationGuid
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("OperationGuid")]
    public partial class ViewDatabaseChangesOperation
    {
        /// <summary>
        /// Create a new ViewDatabaseChangesOperation object.
        /// </summary>
        /// <param name="operationGuid">Initial value of OperationGuid.</param>
        /// <param name="isRegisteredDac">Initial value of IsRegisteredDac.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ViewDatabaseChangesOperation CreateViewDatabaseChangesOperation(global::System.Guid operationGuid, bool isRegisteredDac)
        {
            ViewDatabaseChangesOperation viewDatabaseChangesOperation = new ViewDatabaseChangesOperation();
            viewDatabaseChangesOperation.OperationGuid = operationGuid;
            viewDatabaseChangesOperation.IsRegisteredDac = isRegisteredDac;
            return viewDatabaseChangesOperation;
        }
        /// <summary>
        /// There are no comments for Property OperationGuid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid OperationGuid
        {
            get
            {
                return this._OperationGuid;
            }
            set
            {
                this.OnOperationGuidChanging(value);
                this._OperationGuid = value;
                this.OnOperationGuidChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _OperationGuid;
        partial void OnOperationGuidChanging(global::System.Guid value);
        partial void OnOperationGuidChanged();
        /// <summary>
        /// There are no comments for Property DatabaseName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DatabaseName
        {
            get
            {
                return this._DatabaseName;
            }
            set
            {
                this.OnDatabaseNameChanging(value);
                this._DatabaseName = value;
                this.OnDatabaseNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DatabaseName;
        partial void OnDatabaseNameChanging(string value);
        partial void OnDatabaseNameChanged();
        /// <summary>
        /// There are no comments for Property ChangeResult in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ChangeResult
        {
            get
            {
                return this._ChangeResult;
            }
            set
            {
                this.OnChangeResultChanging(value);
                this._ChangeResult = value;
                this.OnChangeResultChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ChangeResult;
        partial void OnChangeResultChanging(string value);
        partial void OnChangeResultChanged();
        /// <summary>
        /// There are no comments for Property IsRegisteredDac in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsRegisteredDac
        {
            get
            {
                return this._IsRegisteredDac;
            }
            set
            {
                this.OnIsRegisteredDacChanging(value);
                this._IsRegisteredDac = value;
                this.OnIsRegisteredDacChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsRegisteredDac;
        partial void OnIsRegisteredDacChanging(bool value);
        partial void OnIsRegisteredDacChanged();
    }
    /// <summary>
    /// There are no comments for Microsoft.SqlServer.Management.Server.Domain.ViewUpgradePlanOperation in the schema.
    /// </summary>
    /// <KeyProperties>
    /// OperationGuid
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("OperationGuid")]
    public partial class ViewUpgradePlanOperation
    {
        /// <summary>
        /// Create a new ViewUpgradePlanOperation object.
        /// </summary>
        /// <param name="operationGuid">Initial value of OperationGuid.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ViewUpgradePlanOperation CreateViewUpgradePlanOperation(global::System.Guid operationGuid)
        {
            ViewUpgradePlanOperation viewUpgradePlanOperation = new ViewUpgradePlanOperation();
            viewUpgradePlanOperation.OperationGuid = operationGuid;
            return viewUpgradePlanOperation;
        }
        /// <summary>
        /// There are no comments for Property OperationGuid in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid OperationGuid
        {
            get
            {
                return this._OperationGuid;
            }
            set
            {
                this.OnOperationGuidChanging(value);
                this._OperationGuid = value;
                this.OnOperationGuidChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _OperationGuid;
        partial void OnOperationGuidChanging(global::System.Guid value);
        partial void OnOperationGuidChanged();
        /// <summary>
        /// There are no comments for Property DatabaseName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string DatabaseName
        {
            get
            {
                return this._DatabaseName;
            }
            set
            {
                this.OnDatabaseNameChanging(value);
                this._DatabaseName = value;
                this.OnDatabaseNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _DatabaseName;
        partial void OnDatabaseNameChanging(string value);
        partial void OnDatabaseNameChanged();
        /// <summary>
        /// There are no comments for Property DacPac in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] DacPac
        {
            get
            {
                if ((this._DacPac != null))
                {
                    return ((byte[])(this._DacPac.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnDacPacChanging(value);
                this._DacPac = value;
                this.OnDacPacChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _DacPac;
        partial void OnDacPacChanging(byte[] value);
        partial void OnDacPacChanged();
        /// <summary>
        /// There are no comments for Property RollbackOnFailure in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> RollbackOnFailure
        {
            get
            {
                return this._RollbackOnFailure;
            }
            set
            {
                this.OnRollbackOnFailureChanging(value);
                this._RollbackOnFailure = value;
                this.OnRollbackOnFailureChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _RollbackOnFailure;
        partial void OnRollbackOnFailureChanging(global::System.Nullable<bool> value);
        partial void OnRollbackOnFailureChanged();
        /// <summary>
        /// There are no comments for Property UpgradePlan in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UpgradePlan
        {
            get
            {
                return this._UpgradePlan;
            }
            set
            {
                this.OnUpgradePlanChanging(value);
                this._UpgradePlan = value;
                this.OnUpgradePlanChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UpgradePlan;
        partial void OnUpgradePlanChanging(string value);
        partial void OnUpgradePlanChanged();
        /// <summary>
        /// There are no comments for Property UpgradeScript in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string UpgradeScript
        {
            get
            {
                return this._UpgradeScript;
            }
            set
            {
                this.OnUpgradeScriptChanging(value);
                this._UpgradeScript = value;
                this.OnUpgradeScriptChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _UpgradeScript;
        partial void OnUpgradeScriptChanging(string value);
        partial void OnUpgradeScriptChanged();
    }
    /// <summary>
    /// There are no comments for Microsoft.SqlServer.Management.Server.Domain.FirewallRule in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Name
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Name")]
    public partial class FirewallRule
    {
        /// <summary>
        /// Create a new FirewallRule object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="createDate">Initial value of CreateDate.</param>
        /// <param name="modifyDate">Initial value of ModifyDate.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static FirewallRule CreateFirewallRule(string name, global::System.DateTime createDate, global::System.DateTime modifyDate)
        {
            FirewallRule firewallRule = new FirewallRule();
            firewallRule.Name = name;
            firewallRule.CreateDate = createDate;
            firewallRule.ModifyDate = modifyDate;
            return firewallRule;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property StartIPAddress in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string StartIPAddress
        {
            get
            {
                return this._StartIPAddress;
            }
            set
            {
                this.OnStartIPAddressChanging(value);
                this._StartIPAddress = value;
                this.OnStartIPAddressChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _StartIPAddress;
        partial void OnStartIPAddressChanging(string value);
        partial void OnStartIPAddressChanged();
        /// <summary>
        /// There are no comments for Property EndIPAddress in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EndIPAddress
        {
            get
            {
                return this._EndIPAddress;
            }
            set
            {
                this.OnEndIPAddressChanging(value);
                this._EndIPAddress = value;
                this.OnEndIPAddressChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EndIPAddress;
        partial void OnEndIPAddressChanging(string value);
        partial void OnEndIPAddressChanged();
        /// <summary>
        /// There are no comments for Property CreateDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CreateDate
        {
            get
            {
                return this._CreateDate;
            }
            set
            {
                this.OnCreateDateChanging(value);
                this._CreateDate = value;
                this.OnCreateDateChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
        /// <summary>
        /// There are no comments for Property ModifyDate in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime ModifyDate
        {
            get
            {
                return this._ModifyDate;
            }
            set
            {
                this.OnModifyDateChanging(value);
                this._ModifyDate = value;
                this.OnModifyDateChanged();
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _ModifyDate;
        partial void OnModifyDateChanging(global::System.DateTime value);
        partial void OnModifyDateChanged();
    }
}
namespace Microsoft.WindowsAzure.Management.SqlDatabase.Services.Server
{
    public abstract partial class ServerContextInternal
    {
        public readonly string metadataHash = "2D8FBE5BE6D8B2DCA1903ECF43F830A4FEB6A396";
    }
}
