//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Azure.Commands.ManagedCache.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Azure.Commands.ManagedCache.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not able to find the cache service just now created.
        /// </summary>
        internal static string CacheServiceMissing {
            get {
                return ResourceManager.GetString("CacheServiceMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cache service name either has been taken or invalid.
        /// </summary>
        internal static string CacheServiceNameUnavailable {
            get {
                return ResourceManager.GetString("CacheServiceNameUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache Service &apos;{0}&apos; was not found.
        /// </summary>
        internal static string CacheServiceNotFound {
            get {
                return ResourceManager.GetString("CacheServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating cache service....
        /// </summary>
        internal static string CreatingCacheService {
            get {
                return ResourceManager.GetString("CreatingCacheService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating prerequisites....
        /// </summary>
        internal static string CreatingPrerequisites {
            get {
                return ResourceManager.GetString("CreatingPrerequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intializing parameters....
        /// </summary>
        internal static string InitializingCacheParameters {
            get {
                return ResourceManager.GetString("InitializingCacheParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cache memory size. Please specify value between {0} and {1}{2}.
        /// </summary>
        internal static string InvalidCacheMemorySize {
            get {
                return ResourceManager.GetString("InvalidCacheMemorySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cache service name must contain between 6 and 20 characters. It can contain only lowercase letters and numbers, and must start with a letter..
        /// </summary>
        internal static string InvalidCacheServiceName {
            get {
                return ResourceManager.GetString("InvalidCacheServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Sku. Please specify one from &apos;Basic&apos;, &apos;Standard&apos;, or &quot;Premium&quot;..
        /// </summary>
        internal static string InvalidCacheSku {
            get {
                return ResourceManager.GetString("InvalidCacheSku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time out to wait for cache service ready.
        /// </summary>
        internal static string TimeoutWaitForCacheServiceReady {
            get {
                return ResourceManager.GetString("TimeoutWaitForCacheServiceReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify cache service name....
        /// </summary>
        internal static string VerifyingCacheServiceName {
            get {
                return ResourceManager.GetString("VerifyingCacheServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for cache service becomes ready....
        /// </summary>
        internal static string WaitForCacheServiceReady {
            get {
                return ResourceManager.GetString("WaitForCacheServiceReady", resourceCulture);
            }
        }
    }
}
