//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAzure.Commands.Utilities.Common.XmlSchema.ServiceDefinitionSchema
{
    using ServiceDefinitionSchema;

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = false)]
    public partial class RoleModule
    {

        private Startup startupField;

        private RuntimeForRoleModule runtimeField;

        private ConfigurationSetting[] configurationSettingsField;

        private Endpoints endpointsField;

        private LocalResources localResourcesField;

        private Certificate[] certificatesField;

        private Sites sitesField;

        private string namespaceField;

        /// <remarks/>
        public Startup Startup
        {
            get
            {
                return this.startupField;
            }
            set
            {
                this.startupField = value;
            }
        }

        /// <remarks/>
        public RuntimeForRoleModule Runtime
        {
            get
            {
                return this.runtimeField;
            }
            set
            {
                this.runtimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Setting", IsNullable = false)]
        public ConfigurationSetting[] ConfigurationSettings
        {
            get
            {
                return this.configurationSettingsField;
            }
            set
            {
                this.configurationSettingsField = value;
            }
        }

        /// <remarks/>
        public Endpoints Endpoints
        {
            get
            {
                return this.endpointsField;
            }
            set
            {
                this.endpointsField = value;
            }
        }

        /// <remarks/>
        public LocalResources LocalResources
        {
            get
            {
                return this.localResourcesField;
            }
            set
            {
                this.localResourcesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Certificate[] Certificates
        {
            get
            {
                return this.certificatesField;
            }
            set
            {
                this.certificatesField = value;
            }
        }

        /// <remarks/>
        public Sites Sites
        {
            get
            {
                return this.sitesField;
            }
            set
            {
                this.sitesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string @namespace
        {
            get
            {
                return this.namespaceField;
            }
            set
            {
                this.namespaceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class Startup
    {

        private Task[] taskField;

        private int priorityField;

        public Startup()
        {
            this.priorityField = 0;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Task")]
        public Task[] Task
        {
            get
            {
                return this.taskField;
            }
            set
            {
                this.taskField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class Task
    {

        private Variable[] environmentField;

        private string commandLineField;

        private ExecutionContext executionContextField;

        private TaskType taskTypeField;

        public Task()
        {
            this.executionContextField = ExecutionContext.limited;
            this.taskTypeField = TaskType.simple;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Variable[] Environment
        {
            get
            {
                return this.environmentField;
            }
            set
            {
                this.environmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string commandLine
        {
            get
            {
                return this.commandLineField;
            }
            set
            {
                this.commandLineField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ExecutionContext.limited)]
        public ExecutionContext executionContext
        {
            get
            {
                return this.executionContextField;
            }
            set
            {
                this.executionContextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(TaskType.simple)]
        public TaskType taskType
        {
            get
            {
                return this.taskTypeField;
            }
            set
            {
                this.taskTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class Variable
    {

        private RoleInstanceValueElement roleInstanceValueField;

        private string nameField;

        private string valueField;

        /// <remarks/>
        public RoleInstanceValueElement RoleInstanceValue
        {
            get
            {
                return this.roleInstanceValueField;
            }
            set
            {
                this.roleInstanceValueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class RoleInstanceValueElement
    {

        private string xpathField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string xpath
        {
            get
            {
                return this.xpathField;
            }
            set
            {
                this.xpathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class FromRole
    {

        private string roleNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string roleName
        {
            get
            {
                return this.roleNameField;
            }
            set
            {
                this.roleNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class WhenSource
    {

        private FromRole[] fromRoleField;

        private MatchMode matchesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FromRole")]
        public FromRole[] FromRole
        {
            get
            {
                return this.fromRoleField;
            }
            set
            {
                this.fromRoleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public MatchMode matches
        {
            get
            {
                return this.matchesField;
            }
            set
            {
                this.matchesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public enum MatchMode
    {

        /// <remarks/>
        AnyRule,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class AllowAllTraffic
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class RoleEndpoint
    {

        private string roleNameField;

        private string endpointNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string roleName
        {
            get
            {
                return this.roleNameField;
            }
            set
            {
                this.roleNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string endpointName
        {
            get
            {
                return this.endpointNameField;
            }
            set
            {
                this.endpointNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class Destinations
    {

        private RoleEndpoint[] roleEndpointField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RoleEndpoint")]
        public RoleEndpoint[] RoleEndpoint
        {
            get
            {
                return this.roleEndpointField;
            }
            set
            {
                this.roleEndpointField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class OnlyAllowTrafficTo
    {

        private Destinations destinationsField;

        private object itemField;

        /// <remarks/>
        public Destinations Destinations
        {
            get
            {
                return this.destinationsField;
            }
            set
            {
                this.destinationsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AllowAllTraffic", typeof(AllowAllTraffic))]
        [System.Xml.Serialization.XmlElementAttribute("WhenSource", typeof(WhenSource))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class WorkerRole
    {

        private Import[] importsField;

        private Startup startupField;

        private LocalStore localStorageField;

        private LocalResources localResourcesField;

        private ConfigurationSetting[] configurationSettingsField;

        private Endpoints endpointsField;

        private Certificate[] certificatesField;

        private WorkerRuntime runtimeField;

        private ContentElement[] contentsField;

        private string nameField;

        private bool enableNativeCodeExecutionField;

        private RoleSize vmsizeField;

        public WorkerRole()
        {
            this.enableNativeCodeExecutionField = true;
            this.vmsizeField = RoleSize.Small;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Import[] Imports
        {
            get
            {
                return this.importsField;
            }
            set
            {
                this.importsField = value;
            }
        }

        /// <remarks/>
        public Startup Startup
        {
            get
            {
                return this.startupField;
            }
            set
            {
                this.startupField = value;
            }
        }

        /// <remarks/>
        public LocalStore LocalStorage
        {
            get
            {
                return this.localStorageField;
            }
            set
            {
                this.localStorageField = value;
            }
        }

        /// <remarks/>
        public LocalResources LocalResources
        {
            get
            {
                return this.localResourcesField;
            }
            set
            {
                this.localResourcesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Setting", IsNullable = false)]
        public ConfigurationSetting[] ConfigurationSettings
        {
            get
            {
                return this.configurationSettingsField;
            }
            set
            {
                this.configurationSettingsField = value;
            }
        }

        /// <remarks/>
        public Endpoints Endpoints
        {
            get
            {
                return this.endpointsField;
            }
            set
            {
                this.endpointsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable = false)]
        public Certificate[] Certificates
        {
            get
            {
                return this.certificatesField;
            }
            set
            {
                this.certificatesField = value;
            }
        }

        /// <remarks/>
        public WorkerRuntime Runtime
        {
            get
            {
                return this.runtimeField;
            }
            set
            {
                this.runtimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Content", IsNullable = false)]
        public ContentElement[] Contents
        {
            get
            {
                return this.contentsField;
            }
            set
            {
                this.contentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enableNativeCodeExecution
        {
            get
            {
                return this.enableNativeCodeExecutionField;
            }
            set
            {
                this.enableNativeCodeExecutionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(RoleSize.Small)]
        public RoleSize vmsize
        {
            get
            {
                return this.vmsizeField;
            }
            set
            {
                this.vmsizeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class Import
    {

        private string moduleNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string moduleName
        {
            get
            {
                return this.moduleNameField;
            }
            set
            {
                this.moduleNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class LocalStore
    {

        private string nameField;

        private int sizeInMBField;

        private bool cleanOnRoleRecycleField;

        public LocalStore()
        {
            this.sizeInMBField = 1000;
            this.cleanOnRoleRecycleField = true;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(1000)]
        public int sizeInMB
        {
            get
            {
                return this.sizeInMBField;
            }
            set
            {
                this.sizeInMBField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool cleanOnRoleRecycle
        {
            get
            {
                return this.cleanOnRoleRecycleField;
            }
            set
            {
                this.cleanOnRoleRecycleField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class LocalResources
    {

        private LocalStore[] localStorageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LocalStorage")]
        public LocalStore[] LocalStorage
        {
            get
            {
                return this.localStorageField;
            }
            set
            {
                this.localStorageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class ConfigurationSetting
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
}

namespace Microsoft.WindowsAzure.Commands.Utilities.Common.XmlSchema.ServiceDefinitionSchema
{
    using System.Xml.Serialization;
    using Commands.Utilities.Common.XmlSchema.ServiceDefinitionSchema;

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.17929.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class Endpoints
    {

        private InputEndpoint[] inputEndpointField;

        private InternalEndpoint[] internalEndpointField;

        private InstanceInputEndpointElement[] instanceInputEndpointField;

        /// <remarks/>
        [XmlElement("InputEndpoint")]
        public InputEndpoint[] InputEndpoint
        {
            get
            {
                return this.inputEndpointField;
            }
            set
            {
                this.inputEndpointField = value;
            }
        }

        /// <remarks/>
        [XmlElement("InternalEndpoint")]
        public InternalEndpoint[] InternalEndpoint
        {
            get
            {
                return this.internalEndpointField;
            }
            set
            {
                this.internalEndpointField = value;
            }
        }

        /// <remarks/>
        [XmlElement("InstanceInputEndpoint")]
        public InstanceInputEndpointElement[] InstanceInputEndpoint
        {
            get
            {
                return this.instanceInputEndpointField;
            }
            set
            {
                this.instanceInputEndpointField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class InputEndpoint
    {

        private string nameField;

        private Protocol protocolField;

        private int portField;

        private string certificateField;

        private string localPortField;

        private bool ignoreRoleInstanceStatusField;

        private string loadBalancerProbeField;

        public InputEndpoint()
        {
            this.ignoreRoleInstanceStatusField = false;
        }

        /// <remarks/>
        [XmlAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public Protocol protocol
        {
            get
            {
                return this.protocolField;
            }
            set
            {
                this.protocolField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int port
        {
            get
            {
                return this.portField;
            }
            set
            {
                this.portField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string certificate
        {
            get
            {
                return this.certificateField;
            }
            set
            {
                this.certificateField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string localPort
        {
            get
            {
                return this.localPortField;
            }
            set
            {
                this.localPortField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ignoreRoleInstanceStatus
        {
            get
            {
                return this.ignoreRoleInstanceStatusField;
            }
            set
            {
                this.ignoreRoleInstanceStatusField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string loadBalancerProbe
        {
            get
            {
                return this.loadBalancerProbeField;
            }
            set
            {
                this.loadBalancerProbeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public enum Protocol
    {

        /// <remarks/>
        http,

        /// <remarks/>
        https,

        /// <remarks/>
        tcp,

        /// <remarks/>
        udp,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class InternalEndpoint
    {

        private Port[] fixedPortField;

        private PortRange[] fixedPortRangeField;

        private string nameField;

        private string portField;

        private InternalProtocol protocolField;

        /// <remarks/>
        [XmlElement("FixedPort")]
        public Port[] FixedPort
        {
            get
            {
                return this.fixedPortField;
            }
            set
            {
                this.fixedPortField = value;
            }
        }

        /// <remarks/>
        [XmlElement("FixedPortRange")]
        public PortRange[] FixedPortRange
        {
            get
            {
                return this.fixedPortRangeField;
            }
            set
            {
                this.fixedPortRangeField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string port
        {
            get
            {
                return this.portField;
            }
            set
            {
                this.portField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public InternalProtocol protocol
        {
            get
            {
                return this.protocolField;
            }
            set
            {
                this.protocolField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class Port
    {

        private int portField;

        /// <remarks/>
        [XmlAttribute()]
        public int port
        {
            get
            {
                return this.portField;
            }
            set
            {
                this.portField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class PortRange
    {

        private int minField;

        private int maxField;

        /// <remarks/>
        [XmlAttribute()]
        public int min
        {
            get
            {
                return this.minField;
            }
            set
            {
                this.minField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public enum InternalProtocol
    {

        /// <remarks/>
        http,

        /// <remarks/>
        tcp,

        /// <remarks/>
        udp,

        /// <remarks/>
        any,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class InstanceInputEndpointElement
    {

        private AllocatePublicPortFromElement allocatePublicPortFromField;

        private string nameField;

        private int localPortField;

        private TransportProtocol protocolField;

        /// <remarks/>
        public AllocatePublicPortFromElement AllocatePublicPortFrom
        {
            get
            {
                return this.allocatePublicPortFromField;
            }
            set
            {
                this.allocatePublicPortFromField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int localPort
        {
            get
            {
                return this.localPortField;
            }
            set
            {
                this.localPortField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public TransportProtocol protocol
        {
            get
            {
                return this.protocolField;
            }
            set
            {
                this.protocolField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class AllocatePublicPortFromElement
    {

        private PortRange fixedPortRangeField;

        /// <remarks/>
        public PortRange FixedPortRange
        {
            get
            {
                return this.fixedPortRangeField;
            }
            set
            {
                this.fixedPortRangeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public enum TransportProtocol
    {

        /// <remarks/>
        udp,

        /// <remarks/>
        tcp,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class Certificate
    {

        private string nameField;

        private StoreLocation storeLocationField;

        private string storeNameField;

        private PermissionLevel permissionLevelField;

        public Certificate()
        {
            this.permissionLevelField = PermissionLevel.limitedOrElevated;
        }

        /// <remarks/>
        [XmlAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public StoreLocation storeLocation
        {
            get
            {
                return this.storeLocationField;
            }
            set
            {
                this.storeLocationField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string storeName
        {
            get
            {
                return this.storeNameField;
            }
            set
            {
                this.storeNameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(PermissionLevel.limitedOrElevated)]
        public PermissionLevel permissionLevel
        {
            get
            {
                return this.permissionLevelField;
            }
            set
            {
                this.permissionLevelField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public enum StoreLocation
    {

        /// <remarks/>
        CurrentUser,

        /// <remarks/>
        LocalMachine,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public enum PermissionLevel
    {

        /// <remarks/>
        limitedOrElevated,

        /// <remarks/>
        elevated,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class WorkerRuntime : Runtime
    {

        private WorkerEntryPointElement entryPointField;

        /// <remarks/>
        public WorkerEntryPointElement EntryPoint
        {
            get
            {
                return this.entryPointField;
            }
            set
            {
                this.entryPointField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class WorkerEntryPointElement
    {

        private object itemField;

        /// <remarks/>
        [XmlElement("NetFxEntryPoint", typeof(NetFxAssemblyEntryPointElement))]
        [XmlElement("ProgramEntryPoint", typeof(ProgramEntryPointElement))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class NetFxAssemblyEntryPointElement
    {

        private string assemblyNameField;

        private string targetFrameworkVersionField;

        /// <remarks/>
        [XmlAttribute()]
        public string assemblyName
        {
            get
            {
                return this.assemblyNameField;
            }
            set
            {
                this.assemblyNameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string targetFrameworkVersion
        {
            get
            {
                return this.targetFrameworkVersionField;
            }
            set
            {
                this.targetFrameworkVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class ProgramEntryPointElement
    {

        private string commandLineField;

        private bool setReadyOnProcessStartField;

        /// <remarks/>
        [XmlAttribute()]
        public string commandLine
        {
            get
            {
                return this.commandLineField;
            }
            set
            {
                this.commandLineField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public bool setReadyOnProcessStart
        {
            get
            {
                return this.setReadyOnProcessStartField;
            }
            set
            {
                this.setReadyOnProcessStartField = value;
            }
        }
    }

    /// <remarks/>
    [XmlInclude(typeof(RuntimeForRoleModule))]
    [XmlInclude(typeof(WebRuntime))]
    [XmlInclude(typeof(WorkerRuntime))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class Runtime
    {

        private Variable[] environmentField;

        private ExecutionContext executionContextField;

        public Runtime()
        {
            this.executionContextField = ExecutionContext.limited;
        }

        /// <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public Variable[] Environment
        {
            get
            {
                return this.environmentField;
            }
            set
            {
                this.environmentField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(ExecutionContext.limited)]
        public ExecutionContext executionContext
        {
            get
            {
                return this.executionContextField;
            }
            set
            {
                this.executionContextField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public enum ExecutionContext
    {

        /// <remarks/>
        limited,

        /// <remarks/>
        elevated,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class RuntimeForRoleModule : Runtime
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class WebRuntime : Runtime
    {

        private EntryPointElement entryPointField;

        /// <remarks/>
        public EntryPointElement EntryPoint
        {
            get
            {
                return this.entryPointField;
            }
            set
            {
                this.entryPointField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class EntryPointElement
    {

        private NetFxAssemblyEntryPointElement itemField;

        /// <remarks/>
        [XmlElement("NetFxEntryPoint")]
        public NetFxAssemblyEntryPointElement Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class ContentElement
    {

        private SourceDirectoryElement sourceDirectoryField;

        private string destinationField;

        /// <remarks/>
        public SourceDirectoryElement SourceDirectory
        {
            get
            {
                return this.sourceDirectoryField;
            }
            set
            {
                this.sourceDirectoryField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string destination
        {
            get
            {
                return this.destinationField;
            }
            set
            {
                this.destinationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class SourceDirectoryElement
    {

        private string pathField;

        /// <remarks/>
        [XmlAttribute()]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public enum RoleSize
    {

        /// <remarks/>
        ExtraSmall,

        /// <remarks/>
        Small,

        /// <remarks/>
        Medium,

        /// <remarks/>
        Large,

        /// <remarks/>
        ExtraLarge,

        /// <remarks/>
        A5,

        /// <remarks/>
        A6,

        /// <remarks/>
        A7,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class WebRole
    {

        private Import[] importsField;

        private Startup startupField;

        private LocalStore localStorageField;

        private LocalResources localResourcesField;

        private ConfigurationSetting[] configurationSettingsField;

        private WebRoleInputEndpoints inputEndpointsField;

        private WebRoleInternalEndpoint internalEndpointField;

        private Endpoints endpointsField;

        private Certificate[] certificatesField;

        private Sites sitesField;

        private WebRuntime runtimeField;

        private ContentElement[] contentsField;

        private string nameField;

        private bool enableNativeCodeExecutionField;

        private RoleSize vmsizeField;

        public WebRole()
        {
            this.enableNativeCodeExecutionField = true;
            this.vmsizeField = RoleSize.Small;
        }

        /// <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public Import[] Imports
        {
            get
            {
                return this.importsField;
            }
            set
            {
                this.importsField = value;
            }
        }

        /// <remarks/>
        public Startup Startup
        {
            get
            {
                return this.startupField;
            }
            set
            {
                this.startupField = value;
            }
        }

        /// <remarks/>
        public LocalStore LocalStorage
        {
            get
            {
                return this.localStorageField;
            }
            set
            {
                this.localStorageField = value;
            }
        }

        /// <remarks/>
        public LocalResources LocalResources
        {
            get
            {
                return this.localResourcesField;
            }
            set
            {
                this.localResourcesField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("Setting", IsNullable = false)]
        public ConfigurationSetting[] ConfigurationSettings
        {
            get
            {
                return this.configurationSettingsField;
            }
            set
            {
                this.configurationSettingsField = value;
            }
        }

        /// <remarks/>
        public WebRoleInputEndpoints InputEndpoints
        {
            get
            {
                return this.inputEndpointsField;
            }
            set
            {
                this.inputEndpointsField = value;
            }
        }

        /// <remarks/>
        public WebRoleInternalEndpoint InternalEndpoint
        {
            get
            {
                return this.internalEndpointField;
            }
            set
            {
                this.internalEndpointField = value;
            }
        }

        /// <remarks/>
        public Endpoints Endpoints
        {
            get
            {
                return this.endpointsField;
            }
            set
            {
                this.endpointsField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public Certificate[] Certificates
        {
            get
            {
                return this.certificatesField;
            }
            set
            {
                this.certificatesField = value;
            }
        }

        /// <remarks/>
        public Sites Sites
        {
            get
            {
                return this.sitesField;
            }
            set
            {
                this.sitesField = value;
            }
        }

        /// <remarks/>
        public WebRuntime Runtime
        {
            get
            {
                return this.runtimeField;
            }
            set
            {
                this.runtimeField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem("Content", IsNullable = false)]
        public ContentElement[] Contents
        {
            get
            {
                return this.contentsField;
            }
            set
            {
                this.contentsField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enableNativeCodeExecution
        {
            get
            {
                return this.enableNativeCodeExecutionField;
            }
            set
            {
                this.enableNativeCodeExecutionField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(RoleSize.Small)]
        public RoleSize vmsize
        {
            get
            {
                return this.vmsizeField;
            }
            set
            {
                this.vmsizeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class WebRoleInputEndpoints
    {

        private WebRoleInputEndpointsInputEndpoint[] inputEndpointField;

        /// <remarks/>
        [XmlElement("InputEndpoint")]
        public WebRoleInputEndpointsInputEndpoint[] InputEndpoint
        {
            get
            {
                return this.inputEndpointField;
            }
            set
            {
                this.inputEndpointField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class WebRoleInputEndpointsInputEndpoint : InputEndpoint
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType = true, Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class WebRoleInternalEndpoint : InternalEndpoint
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class Sites
    {

        private Site[] siteField;

        /// <remarks/>
        [XmlElement("Site")]
        public Site[] Site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                this.siteField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class Site : VirtualDirectory
    {

        private Binding[] bindingsField;

        /// <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public Binding[] Bindings
        {
            get
            {
                return this.bindingsField;
            }
            set
            {
                this.bindingsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class Binding
    {

        private string nameField;

        private string endpointNameField;

        private string hostHeaderField;

        /// <remarks/>
        [XmlAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string endpointName
        {
            get
            {
                return this.endpointNameField;
            }
            set
            {
                this.endpointNameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string hostHeader
        {
            get
            {
                return this.hostHeaderField;
            }
            set
            {
                this.hostHeaderField = value;
            }
        }
    }

    /// <remarks/>
    [XmlInclude(typeof(VirtualApplication))]
    [XmlInclude(typeof(Site))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class VirtualDirectory
    {

        private VirtualDirectory[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        private string nameField;

        private string physicalDirectoryField;

        /// <remarks/>
        [XmlElement("VirtualApplication", typeof(VirtualDirectory))]
        [XmlElement("VirtualDirectory", typeof(VirtualDirectory))]
        [XmlChoiceIdentifier("ItemsElementName")]
        public VirtualDirectory[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [XmlElement("ItemsElementName")]
        [XmlIgnore()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string physicalDirectory
        {
            get
            {
                return this.physicalDirectoryField;
            }
            set
            {
                this.physicalDirectoryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        VirtualApplication,

        /// <remarks/>
        VirtualDirectory,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class VirtualApplication : VirtualDirectory
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public partial class LoadBalancerProbe
    {

        private string nameField;

        private ProbeProtocol protocolField;

        private int portField;

        private bool portFieldSpecified;

        private string pathField;

        private int intervalInSecondsField;

        private int timeoutInSecondsField;

        public LoadBalancerProbe()
        {
            this.intervalInSecondsField = 15;
            this.timeoutInSecondsField = 31;
        }

        /// <remarks/>
        [XmlAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public ProbeProtocol protocol
        {
            get
            {
                return this.protocolField;
            }
            set
            {
                this.protocolField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public int port
        {
            get
            {
                return this.portField;
            }
            set
            {
                this.portField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool portSpecified
        {
            get
            {
                return this.portFieldSpecified;
            }
            set
            {
                this.portFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(15)]
        public int intervalInSeconds
        {
            get
            {
                return this.intervalInSecondsField;
            }
            set
            {
                this.intervalInSecondsField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(31)]
        public int timeoutInSeconds
        {
            get
            {
                return this.timeoutInSecondsField;
            }
            set
            {
                this.timeoutInSecondsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public enum ProbeProtocol
    {

        /// <remarks/>
        http,

        /// <remarks/>
        tcp,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public enum TaskType
    {

        /// <remarks/>
        simple,

        /// <remarks/>
        foreground,

        /// <remarks/>
        background,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    [XmlRoot(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition", IsNullable = false)]
    public partial class ServiceDefinition
    {

        private LoadBalancerProbe[] loadBalancerProbesField;

        private WebRole[] webRoleField;

        private WorkerRole[] workerRoleField;

        private OnlyAllowTrafficTo[] networkTrafficRulesField;

        private string nameField;

        private int upgradeDomainCountField;

        private SchemaVersion schemaVersionField;

        public ServiceDefinition()
        {
            this.upgradeDomainCountField = 5;
            this.schemaVersionField = SchemaVersion.unspecified;
        }

        /// <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public LoadBalancerProbe[] LoadBalancerProbes
        {
            get
            {
                return this.loadBalancerProbesField;
            }
            set
            {
                this.loadBalancerProbesField = value;
            }
        }

        /// <remarks/>
        [XmlElement("WebRole")]
        public WebRole[] WebRole
        {
            get
            {
                return this.webRoleField;
            }
            set
            {
                this.webRoleField = value;
            }
        }

        /// <remarks/>
        [XmlElement("WorkerRole")]
        public WorkerRole[] WorkerRole
        {
            get
            {
                return this.workerRoleField;
            }
            set
            {
                this.workerRoleField = value;
            }
        }

        /// <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public OnlyAllowTrafficTo[] NetworkTrafficRules
        {
            get
            {
                return this.networkTrafficRulesField;
            }
            set
            {
                this.networkTrafficRulesField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(5)]
        public int upgradeDomainCount
        {
            get
            {
                return this.upgradeDomainCountField;
            }
            set
            {
                this.upgradeDomainCountField = value;
            }
        }

        /// <remarks/>
        [XmlAttribute()]
        [System.ComponentModel.DefaultValueAttribute(SchemaVersion.unspecified)]
        public SchemaVersion schemaVersion
        {
            get
            {
                return this.schemaVersionField;
            }
            set
            {
                this.schemaVersionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [XmlType(Namespace = "http://schemas.microsoft.com/ServiceHosting/2008/10/ServiceDefinition")]
    public enum SchemaVersion
    {

        /// <remarks/>
        unspecified,

        /// <remarks/>
        [XmlEnum("2013-03.2.0")]
        Item20130320,
    }
}